// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/approvalrequest"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ApprovalRequestUpdate is the builder for updating ApprovalRequest entities.
type ApprovalRequestUpdate struct {
	config
	hooks     []Hook
	mutation  *ApprovalRequestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ApprovalRequestUpdate builder.
func (_u *ApprovalRequestUpdate) Where(ps ...predicate.ApprovalRequest) *ApprovalRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApprovalRequestUpdate) SetUpdatedAt(v time.Time) *ApprovalRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ApprovalRequestUpdate) SetMetadata(v map[string]interface{}) *ApprovalRequestUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ApprovalRequestUpdate) ClearMetadata() *ApprovalRequestUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetModule sets the "module" field.
func (_u *ApprovalRequestUpdate) SetModule(v approvalrequest.Module) *ApprovalRequestUpdate {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableModule(v *approvalrequest.Module) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *ApprovalRequestUpdate) SetObjectID(v uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableObjectID(v *uuid.UUID) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// SetObjectReference sets the "object_reference" field.
func (_u *ApprovalRequestUpdate) SetObjectReference(v string) *ApprovalRequestUpdate {
	_u.mutation.SetObjectReference(v)
	return _u
}

// SetNillableObjectReference sets the "object_reference" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableObjectReference(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetObjectReference(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ApprovalRequestUpdate) SetAmount(v decimal.Decimal) *ApprovalRequestUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableAmount(v *decimal.Decimal) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ApprovalRequestUpdate) AddAmount(v decimal.Decimal) *ApprovalRequestUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetPropertyID sets the "property_id" field.
func (_u *ApprovalRequestUpdate) SetPropertyID(v uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.SetPropertyID(v)
	return _u
}

// SetNillablePropertyID sets the "property_id" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillablePropertyID(v *uuid.UUID) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetPropertyID(*v)
	}
	return _u
}

// ClearPropertyID clears the value of the "property_id" field.
func (_u *ApprovalRequestUpdate) ClearPropertyID() *ApprovalRequestUpdate {
	_u.mutation.ClearPropertyID()
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *ApprovalRequestUpdate) SetRuleID(v uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableRuleID(v *uuid.UUID) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// ClearRuleID clears the value of the "rule_id" field.
func (_u *ApprovalRequestUpdate) ClearRuleID() *ApprovalRequestUpdate {
	_u.mutation.ClearRuleID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApprovalRequestUpdate) SetStatus(v approvalrequest.Status) *ApprovalRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableStatus(v *approvalrequest.Status) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentSequence sets the "current_sequence" field.
func (_u *ApprovalRequestUpdate) SetCurrentSequence(v int) *ApprovalRequestUpdate {
	_u.mutation.ResetCurrentSequence()
	_u.mutation.SetCurrentSequence(v)
	return _u
}

// SetNillableCurrentSequence sets the "current_sequence" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableCurrentSequence(v *int) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetCurrentSequence(*v)
	}
	return _u
}

// AddCurrentSequence adds value to the "current_sequence" field.
func (_u *ApprovalRequestUpdate) AddCurrentSequence(v int) *ApprovalRequestUpdate {
	_u.mutation.AddCurrentSequence(v)
	return _u
}

// SetCurrentApprover sets the "current_approver" field.
func (_u *ApprovalRequestUpdate) SetCurrentApprover(v string) *ApprovalRequestUpdate {
	_u.mutation.SetCurrentApprover(v)
	return _u
}

// SetNillableCurrentApprover sets the "current_approver" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableCurrentApprover(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetCurrentApprover(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *ApprovalRequestUpdate) SetActions(v []map[string]interface{}) *ApprovalRequestUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *ApprovalRequestUpdate) AppendActions(v []map[string]interface{}) *ApprovalRequestUpdate {
	_u.mutation.AppendActions(v)
	return _u
}

// SetSubmittedBy sets the "submitted_by" field.
func (_u *ApprovalRequestUpdate) SetSubmittedBy(v uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.SetSubmittedBy(v)
	return _u
}

// SetNillableSubmittedBy sets the "submitted_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableSubmittedBy(v *uuid.UUID) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetSubmittedBy(*v)
	}
	return _u
}

// ClearSubmittedBy clears the value of the "submitted_by" field.
func (_u *ApprovalRequestUpdate) ClearSubmittedBy() *ApprovalRequestUpdate {
	_u.mutation.ClearSubmittedBy()
	return _u
}

// SetSubmittedByName sets the "submitted_by_name" field.
func (_u *ApprovalRequestUpdate) SetSubmittedByName(v string) *ApprovalRequestUpdate {
	_u.mutation.SetSubmittedByName(v)
	return _u
}

// SetNillableSubmittedByName sets the "submitted_by_name" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableSubmittedByName(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetSubmittedByName(*v)
	}
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *ApprovalRequestUpdate) SetDecidedAt(v time.Time) *ApprovalRequestUpdate {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableDecidedAt(v *time.Time) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *ApprovalRequestUpdate) ClearDecidedAt() *ApprovalRequestUpdate {
	_u.mutation.ClearDecidedAt()
	return _u
}

// Mutation returns the ApprovalRequestMutation object of the builder.
func (_u *ApprovalRequestUpdate) Mutation() *ApprovalRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApprovalRequestUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApprovalRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApprovalRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApprovalRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApprovalRequestUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if approvalrequest.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized approvalrequest.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := approvalrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApprovalRequestUpdate) check() error {
	if v, ok := _u.mutation.Module(); ok {
		if err := approvalrequest.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.module": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := approvalrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ApprovalRequestUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ApprovalRequestUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ApprovalRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(approvalrequest.Table, approvalrequest.Columns, sqlgraph.NewFieldSpec(approvalrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(approvalrequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(approvalrequest.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(approvalrequest.FieldModule, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(approvalrequest.FieldObjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ObjectReference(); ok {
		_spec.SetField(approvalrequest.FieldObjectReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(approvalrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(approvalrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PropertyID(); ok {
		_spec.SetField(approvalrequest.FieldPropertyID, field.TypeUUID, value)
	}
	if _u.mutation.PropertyIDCleared() {
		_spec.ClearField(approvalrequest.FieldPropertyID, field.TypeUUID)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(approvalrequest.FieldRuleID, field.TypeUUID, value)
	}
	if _u.mutation.RuleIDCleared() {
		_spec.ClearField(approvalrequest.FieldRuleID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(approvalrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentSequence(); ok {
		_spec.SetField(approvalrequest.FieldCurrentSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentSequence(); ok {
		_spec.AddField(approvalrequest.FieldCurrentSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentApprover(); ok {
		_spec.SetField(approvalrequest.FieldCurrentApprover, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(approvalrequest.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalrequest.FieldActions, value)
		})
	}
	if value, ok := _u.mutation.SubmittedBy(); ok {
		_spec.SetField(approvalrequest.FieldSubmittedBy, field.TypeUUID, value)
	}
	if _u.mutation.SubmittedByCleared() {
		_spec.ClearField(approvalrequest.FieldSubmittedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.SubmittedByName(); ok {
		_spec.SetField(approvalrequest.FieldSubmittedByName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(approvalrequest.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(approvalrequest.FieldDecidedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{approvalrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApprovalRequestUpdateOne is the builder for updating a single ApprovalRequest entity.
type ApprovalRequestUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ApprovalRequestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApprovalRequestUpdateOne) SetUpdatedAt(v time.Time) *ApprovalRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ApprovalRequestUpdateOne) SetMetadata(v map[string]interface{}) *ApprovalRequestUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ApprovalRequestUpdateOne) ClearMetadata() *ApprovalRequestUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetModule sets the "module" field.
func (_u *ApprovalRequestUpdateOne) SetModule(v approvalrequest.Module) *ApprovalRequestUpdateOne {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableModule(v *approvalrequest.Module) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *ApprovalRequestUpdateOne) SetObjectID(v uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableObjectID(v *uuid.UUID) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// SetObjectReference sets the "object_reference" field.
func (_u *ApprovalRequestUpdateOne) SetObjectReference(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetObjectReference(v)
	return _u
}

// SetNillableObjectReference sets the "object_reference" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableObjectReference(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetObjectReference(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ApprovalRequestUpdateOne) SetAmount(v decimal.Decimal) *ApprovalRequestUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableAmount(v *decimal.Decimal) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ApprovalRequestUpdateOne) AddAmount(v decimal.Decimal) *ApprovalRequestUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetPropertyID sets the "property_id" field.
func (_u *ApprovalRequestUpdateOne) SetPropertyID(v uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.SetPropertyID(v)
	return _u
}

// SetNillablePropertyID sets the "property_id" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillablePropertyID(v *uuid.UUID) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetPropertyID(*v)
	}
	return _u
}

// ClearPropertyID clears the value of the "property_id" field.
func (_u *ApprovalRequestUpdateOne) ClearPropertyID() *ApprovalRequestUpdateOne {
	_u.mutation.ClearPropertyID()
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *ApprovalRequestUpdateOne) SetRuleID(v uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableRuleID(v *uuid.UUID) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// ClearRuleID clears the value of the "rule_id" field.
func (_u *ApprovalRequestUpdateOne) ClearRuleID() *ApprovalRequestUpdateOne {
	_u.mutation.ClearRuleID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApprovalRequestUpdateOne) SetStatus(v approvalrequest.Status) *ApprovalRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableStatus(v *approvalrequest.Status) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentSequence sets the "current_sequence" field.
func (_u *ApprovalRequestUpdateOne) SetCurrentSequence(v int) *ApprovalRequestUpdateOne {
	_u.mutation.ResetCurrentSequence()
	_u.mutation.SetCurrentSequence(v)
	return _u
}

// SetNillableCurrentSequence sets the "current_sequence" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableCurrentSequence(v *int) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetCurrentSequence(*v)
	}
	return _u
}

// AddCurrentSequence adds value to the "current_sequence" field.
func (_u *ApprovalRequestUpdateOne) AddCurrentSequence(v int) *ApprovalRequestUpdateOne {
	_u.mutation.AddCurrentSequence(v)
	return _u
}

// SetCurrentApprover sets the "current_approver" field.
func (_u *ApprovalRequestUpdateOne) SetCurrentApprover(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetCurrentApprover(v)
	return _u
}

// SetNillableCurrentApprover sets the "current_approver" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableCurrentApprover(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetCurrentApprover(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *ApprovalRequestUpdateOne) SetActions(v []map[string]interface{}) *ApprovalRequestUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *ApprovalRequestUpdateOne) AppendActions(v []map[string]interface{}) *ApprovalRequestUpdateOne {
	_u.mutation.AppendActions(v)
	return _u
}

// SetSubmittedBy sets the "submitted_by" field.
func (_u *ApprovalRequestUpdateOne) SetSubmittedBy(v uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.SetSubmittedBy(v)
	return _u
}

// SetNillableSubmittedBy sets the "submitted_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableSubmittedBy(v *uuid.UUID) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetSubmittedBy(*v)
	}
	return _u
}

// ClearSubmittedBy clears the value of the "submitted_by" field.
func (_u *ApprovalRequestUpdateOne) ClearSubmittedBy() *ApprovalRequestUpdateOne {
	_u.mutation.ClearSubmittedBy()
	return _u
}

// SetSubmittedByName sets the "submitted_by_name" field.
func (_u *ApprovalRequestUpdateOne) SetSubmittedByName(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetSubmittedByName(v)
	return _u
}

// SetNillableSubmittedByName sets the "submitted_by_name" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableSubmittedByName(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetSubmittedByName(*v)
	}
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *ApprovalRequestUpdateOne) SetDecidedAt(v time.Time) *ApprovalRequestUpdateOne {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableDecidedAt(v *time.Time) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *ApprovalRequestUpdateOne) ClearDecidedAt() *ApprovalRequestUpdateOne {
	_u.mutation.ClearDecidedAt()
	return _u
}

// Mutation returns the ApprovalRequestMutation object of the builder.
func (_u *ApprovalRequestUpdateOne) Mutation() *ApprovalRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the ApprovalRequestUpdate builder.
func (_u *ApprovalRequestUpdateOne) Where(ps ...predicate.ApprovalRequest) *ApprovalRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApprovalRequestUpdateOne) Select(field string, fields ...string) *ApprovalRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApprovalRequest entity.
func (_u *ApprovalRequestUpdateOne) Save(ctx context.Context) (*ApprovalRequest, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApprovalRequestUpdateOne) SaveX(ctx context.Context) *ApprovalRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApprovalRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApprovalRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApprovalRequestUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if approvalrequest.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized approvalrequest.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := approvalrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApprovalRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Module(); ok {
		if err := approvalrequest.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.module": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := approvalrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ApprovalRequestUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ApprovalRequestUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ApprovalRequestUpdateOne) sqlSave(ctx context.Context) (_node *ApprovalRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(approvalrequest.Table, approvalrequest.Columns, sqlgraph.NewFieldSpec(approvalrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApprovalRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, approvalrequest.FieldID)
		for _, f := range fields {
			if !approvalrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != approvalrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(approvalrequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(approvalrequest.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(approvalrequest.FieldModule, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(approvalrequest.FieldObjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ObjectReference(); ok {
		_spec.SetField(approvalrequest.FieldObjectReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(approvalrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(approvalrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PropertyID(); ok {
		_spec.SetField(approvalrequest.FieldPropertyID, field.TypeUUID, value)
	}
	if _u.mutation.PropertyIDCleared() {
		_spec.ClearField(approvalrequest.FieldPropertyID, field.TypeUUID)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(approvalrequest.FieldRuleID, field.TypeUUID, value)
	}
	if _u.mutation.RuleIDCleared() {
		_spec.ClearField(approvalrequest.FieldRuleID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(approvalrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentSequence(); ok {
		_spec.SetField(approvalrequest.FieldCurrentSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentSequence(); ok {
		_spec.AddField(approvalrequest.FieldCurrentSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentApprover(); ok {
		_spec.SetField(approvalrequest.FieldCurrentApprover, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(approvalrequest.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalrequest.FieldActions, value)
		})
	}
	if value, ok := _u.mutation.SubmittedBy(); ok {
		_spec.SetField(approvalrequest.FieldSubmittedBy, field.TypeUUID, value)
	}
	if _u.mutation.SubmittedByCleared() {
		_spec.ClearField(approvalrequest.FieldSubmittedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.SubmittedByName(); ok {
		_spec.SetField(approvalrequest.FieldSubmittedByName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(approvalrequest.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(approvalrequest.FieldDecidedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ApprovalRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{approvalrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
