// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/billingrun"
	"github.com/bengobox/maskani-api/internal/ent/billingrunline"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// BillingRunLineCreate is the builder for creating a BillingRunLine entity.
type BillingRunLineCreate struct {
	config
	mutation *BillingRunLineMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *BillingRunLineCreate) SetTenantID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillingRunLineCreate) SetCreatedAt(v time.Time) *BillingRunLineCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableCreatedAt(v *time.Time) *BillingRunLineCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingRunLineCreate) SetUpdatedAt(v time.Time) *BillingRunLineCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableUpdatedAt(v *time.Time) *BillingRunLineCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *BillingRunLineCreate) SetMetadata(v map[string]interface{}) *BillingRunLineCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *BillingRunLineCreate) SetRunID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetUnitID sets the "unit_id" field.
func (_c *BillingRunLineCreate) SetUnitID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetUnitID(v)
	return _c
}

// SetUnitAccountID sets the "unit_account_id" field.
func (_c *BillingRunLineCreate) SetUnitAccountID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetUnitAccountID(v)
	return _c
}

// SetPartyID sets the "party_id" field.
func (_c *BillingRunLineCreate) SetPartyID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetPartyID(v)
	return _c
}

// SetNillablePartyID sets the "party_id" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillablePartyID(v *uuid.UUID) *BillingRunLineCreate {
	if v != nil {
		_c.SetPartyID(*v)
	}
	return _c
}

// SetUnitCode sets the "unit_code" field.
func (_c *BillingRunLineCreate) SetUnitCode(v string) *BillingRunLineCreate {
	_c.mutation.SetUnitCode(v)
	return _c
}

// SetLines sets the "lines" field.
func (_c *BillingRunLineCreate) SetLines(v []map[string]interface{}) *BillingRunLineCreate {
	_c.mutation.SetLines(v)
	return _c
}

// SetSubtotal sets the "subtotal" field.
func (_c *BillingRunLineCreate) SetSubtotal(v decimal.Decimal) *BillingRunLineCreate {
	_c.mutation.SetSubtotal(v)
	return _c
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableSubtotal(v *decimal.Decimal) *BillingRunLineCreate {
	if v != nil {
		_c.SetSubtotal(*v)
	}
	return _c
}

// SetTaxTotal sets the "tax_total" field.
func (_c *BillingRunLineCreate) SetTaxTotal(v decimal.Decimal) *BillingRunLineCreate {
	_c.mutation.SetTaxTotal(v)
	return _c
}

// SetNillableTaxTotal sets the "tax_total" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableTaxTotal(v *decimal.Decimal) *BillingRunLineCreate {
	if v != nil {
		_c.SetTaxTotal(*v)
	}
	return _c
}

// SetTotal sets the "total" field.
func (_c *BillingRunLineCreate) SetTotal(v decimal.Decimal) *BillingRunLineCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableTotal(v *decimal.Decimal) *BillingRunLineCreate {
	if v != nil {
		_c.SetTotal(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BillingRunLineCreate) SetStatus(v billingrunline.Status) *BillingRunLineCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableStatus(v *billingrunline.Status) *BillingRunLineCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSkipReason sets the "skip_reason" field.
func (_c *BillingRunLineCreate) SetSkipReason(v string) *BillingRunLineCreate {
	_c.mutation.SetSkipReason(v)
	return _c
}

// SetNillableSkipReason sets the "skip_reason" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableSkipReason(v *string) *BillingRunLineCreate {
	if v != nil {
		_c.SetSkipReason(*v)
	}
	return _c
}

// SetTreasuryInvoiceID sets the "treasury_invoice_id" field.
func (_c *BillingRunLineCreate) SetTreasuryInvoiceID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetTreasuryInvoiceID(v)
	return _c
}

// SetNillableTreasuryInvoiceID sets the "treasury_invoice_id" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableTreasuryInvoiceID(v *uuid.UUID) *BillingRunLineCreate {
	if v != nil {
		_c.SetTreasuryInvoiceID(*v)
	}
	return _c
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_c *BillingRunLineCreate) SetInvoiceNumber(v string) *BillingRunLineCreate {
	_c.mutation.SetInvoiceNumber(v)
	return _c
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableInvoiceNumber(v *string) *BillingRunLineCreate {
	if v != nil {
		_c.SetInvoiceNumber(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *BillingRunLineCreate) SetAttempts(v int) *BillingRunLineCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableAttempts(v *int) *BillingRunLineCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *BillingRunLineCreate) SetLastError(v string) *BillingRunLineCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableLastError(v *string) *BillingRunLineCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BillingRunLineCreate) SetID(v uuid.UUID) *BillingRunLineCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BillingRunLineCreate) SetNillableID(v *uuid.UUID) *BillingRunLineCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRun sets the "run" edge to the BillingRun entity.
func (_c *BillingRunLineCreate) SetRun(v *BillingRun) *BillingRunLineCreate {
	return _c.SetRunID(v.ID)
}

// Mutation returns the BillingRunLineMutation object of the builder.
func (_c *BillingRunLineCreate) Mutation() *BillingRunLineMutation {
	return _c.mutation
}

// Save creates the BillingRunLine in the database.
func (_c *BillingRunLineCreate) Save(ctx context.Context) (*BillingRunLine, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingRunLineCreate) SaveX(ctx context.Context) *BillingRunLine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingRunLineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingRunLineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingRunLineCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if billingrunline.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized billingrunline.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := billingrunline.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if billingrunline.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized billingrunline.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := billingrunline.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Subtotal(); !ok {
		if billingrunline.DefaultSubtotal == nil {
			return fmt.Errorf("ent: uninitialized billingrunline.DefaultSubtotal (forgotten import ent/runtime?)")
		}
		v := billingrunline.DefaultSubtotal()
		_c.mutation.SetSubtotal(v)
	}
	if _, ok := _c.mutation.TaxTotal(); !ok {
		if billingrunline.DefaultTaxTotal == nil {
			return fmt.Errorf("ent: uninitialized billingrunline.DefaultTaxTotal (forgotten import ent/runtime?)")
		}
		v := billingrunline.DefaultTaxTotal()
		_c.mutation.SetTaxTotal(v)
	}
	if _, ok := _c.mutation.Total(); !ok {
		if billingrunline.DefaultTotal == nil {
			return fmt.Errorf("ent: uninitialized billingrunline.DefaultTotal (forgotten import ent/runtime?)")
		}
		v := billingrunline.DefaultTotal()
		_c.mutation.SetTotal(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := billingrunline.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := billingrunline.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if billingrunline.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized billingrunline.DefaultID (forgotten import ent/runtime?)")
		}
		v := billingrunline.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingRunLineCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "BillingRunLine.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BillingRunLine.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BillingRunLine.updated_at"`)}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "BillingRunLine.run_id"`)}
	}
	if _, ok := _c.mutation.UnitID(); !ok {
		return &ValidationError{Name: "unit_id", err: errors.New(`ent: missing required field "BillingRunLine.unit_id"`)}
	}
	if _, ok := _c.mutation.UnitAccountID(); !ok {
		return &ValidationError{Name: "unit_account_id", err: errors.New(`ent: missing required field "BillingRunLine.unit_account_id"`)}
	}
	if _, ok := _c.mutation.UnitCode(); !ok {
		return &ValidationError{Name: "unit_code", err: errors.New(`ent: missing required field "BillingRunLine.unit_code"`)}
	}
	if v, ok := _c.mutation.UnitCode(); ok {
		if err := billingrunline.UnitCodeValidator(v); err != nil {
			return &ValidationError{Name: "unit_code", err: fmt.Errorf(`ent: validator failed for field "BillingRunLine.unit_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Lines(); !ok {
		return &ValidationError{Name: "lines", err: errors.New(`ent: missing required field "BillingRunLine.lines"`)}
	}
	if _, ok := _c.mutation.Subtotal(); !ok {
		return &ValidationError{Name: "subtotal", err: errors.New(`ent: missing required field "BillingRunLine.subtotal"`)}
	}
	if _, ok := _c.mutation.TaxTotal(); !ok {
		return &ValidationError{Name: "tax_total", err: errors.New(`ent: missing required field "BillingRunLine.tax_total"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "BillingRunLine.total"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BillingRunLine.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := billingrunline.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingRunLine.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "BillingRunLine.attempts"`)}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "BillingRunLine.run"`)}
	}
	return nil
}

func (_c *BillingRunLineCreate) sqlSave(ctx context.Context) (*BillingRunLine, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingRunLineCreate) createSpec() (*BillingRunLine, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingRunLine{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingrunline.Table, sqlgraph.NewFieldSpec(billingrunline.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(billingrunline.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billingrunline.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingrunline.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(billingrunline.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.UnitID(); ok {
		_spec.SetField(billingrunline.FieldUnitID, field.TypeUUID, value)
		_node.UnitID = value
	}
	if value, ok := _c.mutation.UnitAccountID(); ok {
		_spec.SetField(billingrunline.FieldUnitAccountID, field.TypeUUID, value)
		_node.UnitAccountID = value
	}
	if value, ok := _c.mutation.PartyID(); ok {
		_spec.SetField(billingrunline.FieldPartyID, field.TypeUUID, value)
		_node.PartyID = &value
	}
	if value, ok := _c.mutation.UnitCode(); ok {
		_spec.SetField(billingrunline.FieldUnitCode, field.TypeString, value)
		_node.UnitCode = value
	}
	if value, ok := _c.mutation.Lines(); ok {
		_spec.SetField(billingrunline.FieldLines, field.TypeJSON, value)
		_node.Lines = value
	}
	if value, ok := _c.mutation.Subtotal(); ok {
		_spec.SetField(billingrunline.FieldSubtotal, field.TypeFloat64, value)
		_node.Subtotal = value
	}
	if value, ok := _c.mutation.TaxTotal(); ok {
		_spec.SetField(billingrunline.FieldTaxTotal, field.TypeFloat64, value)
		_node.TaxTotal = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(billingrunline.FieldTotal, field.TypeFloat64, value)
		_node.Total = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(billingrunline.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SkipReason(); ok {
		_spec.SetField(billingrunline.FieldSkipReason, field.TypeString, value)
		_node.SkipReason = value
	}
	if value, ok := _c.mutation.TreasuryInvoiceID(); ok {
		_spec.SetField(billingrunline.FieldTreasuryInvoiceID, field.TypeUUID, value)
		_node.TreasuryInvoiceID = &value
	}
	if value, ok := _c.mutation.InvoiceNumber(); ok {
		_spec.SetField(billingrunline.FieldInvoiceNumber, field.TypeString, value)
		_node.InvoiceNumber = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(billingrunline.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(billingrunline.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingrunline.RunTable,
			Columns: []string{billingrunline.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billingrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingRunLine.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingRunLineUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingRunLineCreate) OnConflict(opts ...sql.ConflictOption) *BillingRunLineUpsertOne {
	_c.conflict = opts
	return &BillingRunLineUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingRunLine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingRunLineCreate) OnConflictColumns(columns ...string) *BillingRunLineUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingRunLineUpsertOne{
		create: _c,
	}
}

type (
	// BillingRunLineUpsertOne is the builder for "upsert"-ing
	//  one BillingRunLine node.
	BillingRunLineUpsertOne struct {
		create *BillingRunLineCreate
	}

	// BillingRunLineUpsert is the "OnConflict" setter.
	BillingRunLineUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingRunLineUpsert) SetUpdatedAt(v time.Time) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateUpdatedAt() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldUpdatedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *BillingRunLineUpsert) SetMetadata(v map[string]interface{}) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateMetadata() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BillingRunLineUpsert) ClearMetadata() *BillingRunLineUpsert {
	u.SetNull(billingrunline.FieldMetadata)
	return u
}

// SetRunID sets the "run_id" field.
func (u *BillingRunLineUpsert) SetRunID(v uuid.UUID) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateRunID() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldRunID)
	return u
}

// SetUnitID sets the "unit_id" field.
func (u *BillingRunLineUpsert) SetUnitID(v uuid.UUID) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldUnitID, v)
	return u
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateUnitID() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldUnitID)
	return u
}

// SetUnitAccountID sets the "unit_account_id" field.
func (u *BillingRunLineUpsert) SetUnitAccountID(v uuid.UUID) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldUnitAccountID, v)
	return u
}

// UpdateUnitAccountID sets the "unit_account_id" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateUnitAccountID() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldUnitAccountID)
	return u
}

// SetPartyID sets the "party_id" field.
func (u *BillingRunLineUpsert) SetPartyID(v uuid.UUID) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldPartyID, v)
	return u
}

// UpdatePartyID sets the "party_id" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdatePartyID() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldPartyID)
	return u
}

// ClearPartyID clears the value of the "party_id" field.
func (u *BillingRunLineUpsert) ClearPartyID() *BillingRunLineUpsert {
	u.SetNull(billingrunline.FieldPartyID)
	return u
}

// SetUnitCode sets the "unit_code" field.
func (u *BillingRunLineUpsert) SetUnitCode(v string) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldUnitCode, v)
	return u
}

// UpdateUnitCode sets the "unit_code" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateUnitCode() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldUnitCode)
	return u
}

// SetLines sets the "lines" field.
func (u *BillingRunLineUpsert) SetLines(v []map[string]interface{}) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldLines, v)
	return u
}

// UpdateLines sets the "lines" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateLines() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldLines)
	return u
}

// SetSubtotal sets the "subtotal" field.
func (u *BillingRunLineUpsert) SetSubtotal(v decimal.Decimal) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldSubtotal, v)
	return u
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateSubtotal() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldSubtotal)
	return u
}

// AddSubtotal adds v to the "subtotal" field.
func (u *BillingRunLineUpsert) AddSubtotal(v decimal.Decimal) *BillingRunLineUpsert {
	u.Add(billingrunline.FieldSubtotal, v)
	return u
}

// SetTaxTotal sets the "tax_total" field.
func (u *BillingRunLineUpsert) SetTaxTotal(v decimal.Decimal) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldTaxTotal, v)
	return u
}

// UpdateTaxTotal sets the "tax_total" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateTaxTotal() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldTaxTotal)
	return u
}

// AddTaxTotal adds v to the "tax_total" field.
func (u *BillingRunLineUpsert) AddTaxTotal(v decimal.Decimal) *BillingRunLineUpsert {
	u.Add(billingrunline.FieldTaxTotal, v)
	return u
}

// SetTotal sets the "total" field.
func (u *BillingRunLineUpsert) SetTotal(v decimal.Decimal) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldTotal, v)
	return u
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateTotal() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldTotal)
	return u
}

// AddTotal adds v to the "total" field.
func (u *BillingRunLineUpsert) AddTotal(v decimal.Decimal) *BillingRunLineUpsert {
	u.Add(billingrunline.FieldTotal, v)
	return u
}

// SetStatus sets the "status" field.
func (u *BillingRunLineUpsert) SetStatus(v billingrunline.Status) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateStatus() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldStatus)
	return u
}

// SetSkipReason sets the "skip_reason" field.
func (u *BillingRunLineUpsert) SetSkipReason(v string) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldSkipReason, v)
	return u
}

// UpdateSkipReason sets the "skip_reason" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateSkipReason() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldSkipReason)
	return u
}

// ClearSkipReason clears the value of the "skip_reason" field.
func (u *BillingRunLineUpsert) ClearSkipReason() *BillingRunLineUpsert {
	u.SetNull(billingrunline.FieldSkipReason)
	return u
}

// SetTreasuryInvoiceID sets the "treasury_invoice_id" field.
func (u *BillingRunLineUpsert) SetTreasuryInvoiceID(v uuid.UUID) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldTreasuryInvoiceID, v)
	return u
}

// UpdateTreasuryInvoiceID sets the "treasury_invoice_id" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateTreasuryInvoiceID() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldTreasuryInvoiceID)
	return u
}

// ClearTreasuryInvoiceID clears the value of the "treasury_invoice_id" field.
func (u *BillingRunLineUpsert) ClearTreasuryInvoiceID() *BillingRunLineUpsert {
	u.SetNull(billingrunline.FieldTreasuryInvoiceID)
	return u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *BillingRunLineUpsert) SetInvoiceNumber(v string) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldInvoiceNumber, v)
	return u
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateInvoiceNumber() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldInvoiceNumber)
	return u
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *BillingRunLineUpsert) ClearInvoiceNumber() *BillingRunLineUpsert {
	u.SetNull(billingrunline.FieldInvoiceNumber)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *BillingRunLineUpsert) SetAttempts(v int) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateAttempts() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *BillingRunLineUpsert) AddAttempts(v int) *BillingRunLineUpsert {
	u.Add(billingrunline.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *BillingRunLineUpsert) SetLastError(v string) *BillingRunLineUpsert {
	u.Set(billingrunline.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BillingRunLineUpsert) UpdateLastError() *BillingRunLineUpsert {
	u.SetExcluded(billingrunline.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *BillingRunLineUpsert) ClearLastError() *BillingRunLineUpsert {
	u.SetNull(billingrunline.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BillingRunLine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(billingrunline.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BillingRunLineUpsertOne) UpdateNewValues() *BillingRunLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(billingrunline.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(billingrunline.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(billingrunline.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingRunLine.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BillingRunLineUpsertOne) Ignore() *BillingRunLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingRunLineUpsertOne) DoNothing() *BillingRunLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingRunLineCreate.OnConflict
// documentation for more info.
func (u *BillingRunLineUpsertOne) Update(set func(*BillingRunLineUpsert)) *BillingRunLineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingRunLineUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingRunLineUpsertOne) SetUpdatedAt(v time.Time) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateUpdatedAt() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BillingRunLineUpsertOne) SetMetadata(v map[string]interface{}) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateMetadata() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BillingRunLineUpsertOne) ClearMetadata() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearMetadata()
	})
}

// SetRunID sets the "run_id" field.
func (u *BillingRunLineUpsertOne) SetRunID(v uuid.UUID) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateRunID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateRunID()
	})
}

// SetUnitID sets the "unit_id" field.
func (u *BillingRunLineUpsertOne) SetUnitID(v uuid.UUID) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUnitID(v)
	})
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateUnitID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUnitID()
	})
}

// SetUnitAccountID sets the "unit_account_id" field.
func (u *BillingRunLineUpsertOne) SetUnitAccountID(v uuid.UUID) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUnitAccountID(v)
	})
}

// UpdateUnitAccountID sets the "unit_account_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateUnitAccountID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUnitAccountID()
	})
}

// SetPartyID sets the "party_id" field.
func (u *BillingRunLineUpsertOne) SetPartyID(v uuid.UUID) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetPartyID(v)
	})
}

// UpdatePartyID sets the "party_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdatePartyID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdatePartyID()
	})
}

// ClearPartyID clears the value of the "party_id" field.
func (u *BillingRunLineUpsertOne) ClearPartyID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearPartyID()
	})
}

// SetUnitCode sets the "unit_code" field.
func (u *BillingRunLineUpsertOne) SetUnitCode(v string) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUnitCode(v)
	})
}

// UpdateUnitCode sets the "unit_code" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateUnitCode() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUnitCode()
	})
}

// SetLines sets the "lines" field.
func (u *BillingRunLineUpsertOne) SetLines(v []map[string]interface{}) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetLines(v)
	})
}

// UpdateLines sets the "lines" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateLines() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateLines()
	})
}

// SetSubtotal sets the "subtotal" field.
func (u *BillingRunLineUpsertOne) SetSubtotal(v decimal.Decimal) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetSubtotal(v)
	})
}

// AddSubtotal adds v to the "subtotal" field.
func (u *BillingRunLineUpsertOne) AddSubtotal(v decimal.Decimal) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddSubtotal(v)
	})
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateSubtotal() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateSubtotal()
	})
}

// SetTaxTotal sets the "tax_total" field.
func (u *BillingRunLineUpsertOne) SetTaxTotal(v decimal.Decimal) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetTaxTotal(v)
	})
}

// AddTaxTotal adds v to the "tax_total" field.
func (u *BillingRunLineUpsertOne) AddTaxTotal(v decimal.Decimal) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddTaxTotal(v)
	})
}

// UpdateTaxTotal sets the "tax_total" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateTaxTotal() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateTaxTotal()
	})
}

// SetTotal sets the "total" field.
func (u *BillingRunLineUpsertOne) SetTotal(v decimal.Decimal) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *BillingRunLineUpsertOne) AddTotal(v decimal.Decimal) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateTotal() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateTotal()
	})
}

// SetStatus sets the "status" field.
func (u *BillingRunLineUpsertOne) SetStatus(v billingrunline.Status) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateStatus() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateStatus()
	})
}

// SetSkipReason sets the "skip_reason" field.
func (u *BillingRunLineUpsertOne) SetSkipReason(v string) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetSkipReason(v)
	})
}

// UpdateSkipReason sets the "skip_reason" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateSkipReason() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateSkipReason()
	})
}

// ClearSkipReason clears the value of the "skip_reason" field.
func (u *BillingRunLineUpsertOne) ClearSkipReason() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearSkipReason()
	})
}

// SetTreasuryInvoiceID sets the "treasury_invoice_id" field.
func (u *BillingRunLineUpsertOne) SetTreasuryInvoiceID(v uuid.UUID) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetTreasuryInvoiceID(v)
	})
}

// UpdateTreasuryInvoiceID sets the "treasury_invoice_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateTreasuryInvoiceID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateTreasuryInvoiceID()
	})
}

// ClearTreasuryInvoiceID clears the value of the "treasury_invoice_id" field.
func (u *BillingRunLineUpsertOne) ClearTreasuryInvoiceID() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearTreasuryInvoiceID()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *BillingRunLineUpsertOne) SetInvoiceNumber(v string) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateInvoiceNumber() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *BillingRunLineUpsertOne) ClearInvoiceNumber() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearInvoiceNumber()
	})
}

// SetAttempts sets the "attempts" field.
func (u *BillingRunLineUpsertOne) SetAttempts(v int) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *BillingRunLineUpsertOne) AddAttempts(v int) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateAttempts() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *BillingRunLineUpsertOne) SetLastError(v string) *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BillingRunLineUpsertOne) UpdateLastError() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *BillingRunLineUpsertOne) ClearLastError() *BillingRunLineUpsertOne {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *BillingRunLineUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingRunLineCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingRunLineUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BillingRunLineUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BillingRunLineUpsertOne.ID is not supported by MySQL driver. Use BillingRunLineUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BillingRunLineUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BillingRunLineCreateBulk is the builder for creating many BillingRunLine entities in bulk.
type BillingRunLineCreateBulk struct {
	config
	err      error
	builders []*BillingRunLineCreate
	conflict []sql.ConflictOption
}

// Save creates the BillingRunLine entities in the database.
func (_c *BillingRunLineCreateBulk) Save(ctx context.Context) ([]*BillingRunLine, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingRunLine, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingRunLineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingRunLineCreateBulk) SaveX(ctx context.Context) []*BillingRunLine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingRunLineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingRunLineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingRunLine.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingRunLineUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingRunLineCreateBulk) OnConflict(opts ...sql.ConflictOption) *BillingRunLineUpsertBulk {
	_c.conflict = opts
	return &BillingRunLineUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingRunLine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingRunLineCreateBulk) OnConflictColumns(columns ...string) *BillingRunLineUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingRunLineUpsertBulk{
		create: _c,
	}
}

// BillingRunLineUpsertBulk is the builder for "upsert"-ing
// a bulk of BillingRunLine nodes.
type BillingRunLineUpsertBulk struct {
	create *BillingRunLineCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BillingRunLine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(billingrunline.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BillingRunLineUpsertBulk) UpdateNewValues() *BillingRunLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(billingrunline.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(billingrunline.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(billingrunline.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingRunLine.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BillingRunLineUpsertBulk) Ignore() *BillingRunLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingRunLineUpsertBulk) DoNothing() *BillingRunLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingRunLineCreateBulk.OnConflict
// documentation for more info.
func (u *BillingRunLineUpsertBulk) Update(set func(*BillingRunLineUpsert)) *BillingRunLineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingRunLineUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingRunLineUpsertBulk) SetUpdatedAt(v time.Time) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateUpdatedAt() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BillingRunLineUpsertBulk) SetMetadata(v map[string]interface{}) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateMetadata() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BillingRunLineUpsertBulk) ClearMetadata() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearMetadata()
	})
}

// SetRunID sets the "run_id" field.
func (u *BillingRunLineUpsertBulk) SetRunID(v uuid.UUID) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateRunID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateRunID()
	})
}

// SetUnitID sets the "unit_id" field.
func (u *BillingRunLineUpsertBulk) SetUnitID(v uuid.UUID) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUnitID(v)
	})
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateUnitID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUnitID()
	})
}

// SetUnitAccountID sets the "unit_account_id" field.
func (u *BillingRunLineUpsertBulk) SetUnitAccountID(v uuid.UUID) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUnitAccountID(v)
	})
}

// UpdateUnitAccountID sets the "unit_account_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateUnitAccountID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUnitAccountID()
	})
}

// SetPartyID sets the "party_id" field.
func (u *BillingRunLineUpsertBulk) SetPartyID(v uuid.UUID) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetPartyID(v)
	})
}

// UpdatePartyID sets the "party_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdatePartyID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdatePartyID()
	})
}

// ClearPartyID clears the value of the "party_id" field.
func (u *BillingRunLineUpsertBulk) ClearPartyID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearPartyID()
	})
}

// SetUnitCode sets the "unit_code" field.
func (u *BillingRunLineUpsertBulk) SetUnitCode(v string) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetUnitCode(v)
	})
}

// UpdateUnitCode sets the "unit_code" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateUnitCode() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateUnitCode()
	})
}

// SetLines sets the "lines" field.
func (u *BillingRunLineUpsertBulk) SetLines(v []map[string]interface{}) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetLines(v)
	})
}

// UpdateLines sets the "lines" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateLines() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateLines()
	})
}

// SetSubtotal sets the "subtotal" field.
func (u *BillingRunLineUpsertBulk) SetSubtotal(v decimal.Decimal) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetSubtotal(v)
	})
}

// AddSubtotal adds v to the "subtotal" field.
func (u *BillingRunLineUpsertBulk) AddSubtotal(v decimal.Decimal) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddSubtotal(v)
	})
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateSubtotal() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateSubtotal()
	})
}

// SetTaxTotal sets the "tax_total" field.
func (u *BillingRunLineUpsertBulk) SetTaxTotal(v decimal.Decimal) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetTaxTotal(v)
	})
}

// AddTaxTotal adds v to the "tax_total" field.
func (u *BillingRunLineUpsertBulk) AddTaxTotal(v decimal.Decimal) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddTaxTotal(v)
	})
}

// UpdateTaxTotal sets the "tax_total" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateTaxTotal() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateTaxTotal()
	})
}

// SetTotal sets the "total" field.
func (u *BillingRunLineUpsertBulk) SetTotal(v decimal.Decimal) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *BillingRunLineUpsertBulk) AddTotal(v decimal.Decimal) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateTotal() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateTotal()
	})
}

// SetStatus sets the "status" field.
func (u *BillingRunLineUpsertBulk) SetStatus(v billingrunline.Status) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateStatus() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateStatus()
	})
}

// SetSkipReason sets the "skip_reason" field.
func (u *BillingRunLineUpsertBulk) SetSkipReason(v string) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetSkipReason(v)
	})
}

// UpdateSkipReason sets the "skip_reason" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateSkipReason() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateSkipReason()
	})
}

// ClearSkipReason clears the value of the "skip_reason" field.
func (u *BillingRunLineUpsertBulk) ClearSkipReason() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearSkipReason()
	})
}

// SetTreasuryInvoiceID sets the "treasury_invoice_id" field.
func (u *BillingRunLineUpsertBulk) SetTreasuryInvoiceID(v uuid.UUID) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetTreasuryInvoiceID(v)
	})
}

// UpdateTreasuryInvoiceID sets the "treasury_invoice_id" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateTreasuryInvoiceID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateTreasuryInvoiceID()
	})
}

// ClearTreasuryInvoiceID clears the value of the "treasury_invoice_id" field.
func (u *BillingRunLineUpsertBulk) ClearTreasuryInvoiceID() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearTreasuryInvoiceID()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *BillingRunLineUpsertBulk) SetInvoiceNumber(v string) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateInvoiceNumber() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *BillingRunLineUpsertBulk) ClearInvoiceNumber() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearInvoiceNumber()
	})
}

// SetAttempts sets the "attempts" field.
func (u *BillingRunLineUpsertBulk) SetAttempts(v int) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *BillingRunLineUpsertBulk) AddAttempts(v int) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateAttempts() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *BillingRunLineUpsertBulk) SetLastError(v string) *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BillingRunLineUpsertBulk) UpdateLastError() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *BillingRunLineUpsertBulk) ClearLastError() *BillingRunLineUpsertBulk {
	return u.Update(func(s *BillingRunLineUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *BillingRunLineUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BillingRunLineCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingRunLineCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingRunLineUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
