// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/documentsignature"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
)

// DocumentSignatureDelete is the builder for deleting a DocumentSignature entity.
type DocumentSignatureDelete struct {
	config
	hooks    []Hook
	mutation *DocumentSignatureMutation
}

// Where appends a list predicates to the DocumentSignatureDelete builder.
func (_d *DocumentSignatureDelete) Where(ps ...predicate.DocumentSignature) *DocumentSignatureDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DocumentSignatureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DocumentSignatureDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DocumentSignatureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(documentsignature.Table, sqlgraph.NewFieldSpec(documentsignature.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DocumentSignatureDeleteOne is the builder for deleting a single DocumentSignature entity.
type DocumentSignatureDeleteOne struct {
	_d *DocumentSignatureDelete
}

// Where appends a list predicates to the DocumentSignatureDelete builder.
func (_d *DocumentSignatureDeleteOne) Where(ps ...predicate.DocumentSignature) *DocumentSignatureDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DocumentSignatureDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{documentsignature.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DocumentSignatureDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
