// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/fund"
	"github.com/bengobox/maskani-api/internal/ent/unitaccount"
	"github.com/google/uuid"
)

// FundCreate is the builder for creating a Fund entity.
type FundCreate struct {
	config
	mutation *FundMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *FundCreate) SetTenantID(v uuid.UUID) *FundCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FundCreate) SetCreatedAt(v time.Time) *FundCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FundCreate) SetNillableCreatedAt(v *time.Time) *FundCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FundCreate) SetUpdatedAt(v time.Time) *FundCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FundCreate) SetNillableUpdatedAt(v *time.Time) *FundCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *FundCreate) SetMetadata(v map[string]interface{}) *FundCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *FundCreate) SetCode(v string) *FundCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *FundCreate) SetName(v string) *FundCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *FundCreate) SetKind(v fund.Kind) *FundCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *FundCreate) SetNillableKind(v *fund.Kind) *FundCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetTreasuryBankAccountID sets the "treasury_bank_account_id" field.
func (_c *FundCreate) SetTreasuryBankAccountID(v uuid.UUID) *FundCreate {
	_c.mutation.SetTreasuryBankAccountID(v)
	return _c
}

// SetNillableTreasuryBankAccountID sets the "treasury_bank_account_id" field if the given value is not nil.
func (_c *FundCreate) SetNillableTreasuryBankAccountID(v *uuid.UUID) *FundCreate {
	if v != nil {
		_c.SetTreasuryBankAccountID(*v)
	}
	return _c
}

// SetPaybillShortcode sets the "paybill_shortcode" field.
func (_c *FundCreate) SetPaybillShortcode(v string) *FundCreate {
	_c.mutation.SetPaybillShortcode(v)
	return _c
}

// SetNillablePaybillShortcode sets the "paybill_shortcode" field if the given value is not nil.
func (_c *FundCreate) SetNillablePaybillShortcode(v *string) *FundCreate {
	if v != nil {
		_c.SetPaybillShortcode(*v)
	}
	return _c
}

// SetAccountPrefix sets the "account_prefix" field.
func (_c *FundCreate) SetAccountPrefix(v string) *FundCreate {
	_c.mutation.SetAccountPrefix(v)
	return _c
}

// SetNillableAccountPrefix sets the "account_prefix" field if the given value is not nil.
func (_c *FundCreate) SetNillableAccountPrefix(v *string) *FundCreate {
	if v != nil {
		_c.SetAccountPrefix(*v)
	}
	return _c
}

// SetCostCenterCode sets the "cost_center_code" field.
func (_c *FundCreate) SetCostCenterCode(v string) *FundCreate {
	_c.mutation.SetCostCenterCode(v)
	return _c
}

// SetNillableCostCenterCode sets the "cost_center_code" field if the given value is not nil.
func (_c *FundCreate) SetNillableCostCenterCode(v *string) *FundCreate {
	if v != nil {
		_c.SetCostCenterCode(*v)
	}
	return _c
}

// SetIncomeAccountCode sets the "income_account_code" field.
func (_c *FundCreate) SetIncomeAccountCode(v string) *FundCreate {
	_c.mutation.SetIncomeAccountCode(v)
	return _c
}

// SetNillableIncomeAccountCode sets the "income_account_code" field if the given value is not nil.
func (_c *FundCreate) SetNillableIncomeAccountCode(v *string) *FundCreate {
	if v != nil {
		_c.SetIncomeAccountCode(*v)
	}
	return _c
}

// SetReceivableAccountCode sets the "receivable_account_code" field.
func (_c *FundCreate) SetReceivableAccountCode(v string) *FundCreate {
	_c.mutation.SetReceivableAccountCode(v)
	return _c
}

// SetNillableReceivableAccountCode sets the "receivable_account_code" field if the given value is not nil.
func (_c *FundCreate) SetNillableReceivableAccountCode(v *string) *FundCreate {
	if v != nil {
		_c.SetReceivableAccountCode(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *FundCreate) SetIsDefault(v bool) *FundCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *FundCreate) SetNillableIsDefault(v *bool) *FundCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FundCreate) SetStatus(v fund.Status) *FundCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FundCreate) SetNillableStatus(v *fund.Status) *FundCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FundCreate) SetID(v uuid.UUID) *FundCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FundCreate) SetNillableID(v *uuid.UUID) *FundCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the UnitAccount entity by IDs.
func (_c *FundCreate) AddAccountIDs(ids ...uuid.UUID) *FundCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the UnitAccount entity.
func (_c *FundCreate) AddAccounts(v ...*UnitAccount) *FundCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the FundMutation object of the builder.
func (_c *FundCreate) Mutation() *FundMutation {
	return _c.mutation
}

// Save creates the Fund in the database.
func (_c *FundCreate) Save(ctx context.Context) (*Fund, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FundCreate) SaveX(ctx context.Context) *Fund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FundCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if fund.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized fund.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := fund.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if fund.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized fund.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := fund.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := fund.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := fund.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := fund.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if fund.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized fund.DefaultID (forgotten import ent/runtime?)")
		}
		v := fund.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FundCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Fund.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Fund.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Fund.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Fund.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := fund.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Fund.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Fund.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := fund.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Fund.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Fund.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := fund.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Fund.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "Fund.is_default"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Fund.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := fund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Fund.status": %w`, err)}
		}
	}
	return nil
}

func (_c *FundCreate) sqlSave(ctx context.Context) (*Fund, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FundCreate) createSpec() (*Fund, *sqlgraph.CreateSpec) {
	var (
		_node = &Fund{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fund.Table, sqlgraph.NewFieldSpec(fund.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(fund.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fund.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fund.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(fund.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(fund.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(fund.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(fund.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.TreasuryBankAccountID(); ok {
		_spec.SetField(fund.FieldTreasuryBankAccountID, field.TypeUUID, value)
		_node.TreasuryBankAccountID = &value
	}
	if value, ok := _c.mutation.PaybillShortcode(); ok {
		_spec.SetField(fund.FieldPaybillShortcode, field.TypeString, value)
		_node.PaybillShortcode = value
	}
	if value, ok := _c.mutation.AccountPrefix(); ok {
		_spec.SetField(fund.FieldAccountPrefix, field.TypeString, value)
		_node.AccountPrefix = value
	}
	if value, ok := _c.mutation.CostCenterCode(); ok {
		_spec.SetField(fund.FieldCostCenterCode, field.TypeString, value)
		_node.CostCenterCode = value
	}
	if value, ok := _c.mutation.IncomeAccountCode(); ok {
		_spec.SetField(fund.FieldIncomeAccountCode, field.TypeString, value)
		_node.IncomeAccountCode = value
	}
	if value, ok := _c.mutation.ReceivableAccountCode(); ok {
		_spec.SetField(fund.FieldReceivableAccountCode, field.TypeString, value)
		_node.ReceivableAccountCode = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(fund.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(fund.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fund.AccountsTable,
			Columns: []string{fund.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unitaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Fund.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FundUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *FundCreate) OnConflict(opts ...sql.ConflictOption) *FundUpsertOne {
	_c.conflict = opts
	return &FundUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Fund.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FundCreate) OnConflictColumns(columns ...string) *FundUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FundUpsertOne{
		create: _c,
	}
}

type (
	// FundUpsertOne is the builder for "upsert"-ing
	//  one Fund node.
	FundUpsertOne struct {
		create *FundCreate
	}

	// FundUpsert is the "OnConflict" setter.
	FundUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FundUpsert) SetUpdatedAt(v time.Time) *FundUpsert {
	u.Set(fund.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FundUpsert) UpdateUpdatedAt() *FundUpsert {
	u.SetExcluded(fund.FieldUpdatedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *FundUpsert) SetMetadata(v map[string]interface{}) *FundUpsert {
	u.Set(fund.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *FundUpsert) UpdateMetadata() *FundUpsert {
	u.SetExcluded(fund.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *FundUpsert) ClearMetadata() *FundUpsert {
	u.SetNull(fund.FieldMetadata)
	return u
}

// SetCode sets the "code" field.
func (u *FundUpsert) SetCode(v string) *FundUpsert {
	u.Set(fund.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *FundUpsert) UpdateCode() *FundUpsert {
	u.SetExcluded(fund.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *FundUpsert) SetName(v string) *FundUpsert {
	u.Set(fund.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FundUpsert) UpdateName() *FundUpsert {
	u.SetExcluded(fund.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *FundUpsert) SetKind(v fund.Kind) *FundUpsert {
	u.Set(fund.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *FundUpsert) UpdateKind() *FundUpsert {
	u.SetExcluded(fund.FieldKind)
	return u
}

// SetTreasuryBankAccountID sets the "treasury_bank_account_id" field.
func (u *FundUpsert) SetTreasuryBankAccountID(v uuid.UUID) *FundUpsert {
	u.Set(fund.FieldTreasuryBankAccountID, v)
	return u
}

// UpdateTreasuryBankAccountID sets the "treasury_bank_account_id" field to the value that was provided on create.
func (u *FundUpsert) UpdateTreasuryBankAccountID() *FundUpsert {
	u.SetExcluded(fund.FieldTreasuryBankAccountID)
	return u
}

// ClearTreasuryBankAccountID clears the value of the "treasury_bank_account_id" field.
func (u *FundUpsert) ClearTreasuryBankAccountID() *FundUpsert {
	u.SetNull(fund.FieldTreasuryBankAccountID)
	return u
}

// SetPaybillShortcode sets the "paybill_shortcode" field.
func (u *FundUpsert) SetPaybillShortcode(v string) *FundUpsert {
	u.Set(fund.FieldPaybillShortcode, v)
	return u
}

// UpdatePaybillShortcode sets the "paybill_shortcode" field to the value that was provided on create.
func (u *FundUpsert) UpdatePaybillShortcode() *FundUpsert {
	u.SetExcluded(fund.FieldPaybillShortcode)
	return u
}

// ClearPaybillShortcode clears the value of the "paybill_shortcode" field.
func (u *FundUpsert) ClearPaybillShortcode() *FundUpsert {
	u.SetNull(fund.FieldPaybillShortcode)
	return u
}

// SetAccountPrefix sets the "account_prefix" field.
func (u *FundUpsert) SetAccountPrefix(v string) *FundUpsert {
	u.Set(fund.FieldAccountPrefix, v)
	return u
}

// UpdateAccountPrefix sets the "account_prefix" field to the value that was provided on create.
func (u *FundUpsert) UpdateAccountPrefix() *FundUpsert {
	u.SetExcluded(fund.FieldAccountPrefix)
	return u
}

// ClearAccountPrefix clears the value of the "account_prefix" field.
func (u *FundUpsert) ClearAccountPrefix() *FundUpsert {
	u.SetNull(fund.FieldAccountPrefix)
	return u
}

// SetCostCenterCode sets the "cost_center_code" field.
func (u *FundUpsert) SetCostCenterCode(v string) *FundUpsert {
	u.Set(fund.FieldCostCenterCode, v)
	return u
}

// UpdateCostCenterCode sets the "cost_center_code" field to the value that was provided on create.
func (u *FundUpsert) UpdateCostCenterCode() *FundUpsert {
	u.SetExcluded(fund.FieldCostCenterCode)
	return u
}

// ClearCostCenterCode clears the value of the "cost_center_code" field.
func (u *FundUpsert) ClearCostCenterCode() *FundUpsert {
	u.SetNull(fund.FieldCostCenterCode)
	return u
}

// SetIncomeAccountCode sets the "income_account_code" field.
func (u *FundUpsert) SetIncomeAccountCode(v string) *FundUpsert {
	u.Set(fund.FieldIncomeAccountCode, v)
	return u
}

// UpdateIncomeAccountCode sets the "income_account_code" field to the value that was provided on create.
func (u *FundUpsert) UpdateIncomeAccountCode() *FundUpsert {
	u.SetExcluded(fund.FieldIncomeAccountCode)
	return u
}

// ClearIncomeAccountCode clears the value of the "income_account_code" field.
func (u *FundUpsert) ClearIncomeAccountCode() *FundUpsert {
	u.SetNull(fund.FieldIncomeAccountCode)
	return u
}

// SetReceivableAccountCode sets the "receivable_account_code" field.
func (u *FundUpsert) SetReceivableAccountCode(v string) *FundUpsert {
	u.Set(fund.FieldReceivableAccountCode, v)
	return u
}

// UpdateReceivableAccountCode sets the "receivable_account_code" field to the value that was provided on create.
func (u *FundUpsert) UpdateReceivableAccountCode() *FundUpsert {
	u.SetExcluded(fund.FieldReceivableAccountCode)
	return u
}

// ClearReceivableAccountCode clears the value of the "receivable_account_code" field.
func (u *FundUpsert) ClearReceivableAccountCode() *FundUpsert {
	u.SetNull(fund.FieldReceivableAccountCode)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *FundUpsert) SetIsDefault(v bool) *FundUpsert {
	u.Set(fund.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *FundUpsert) UpdateIsDefault() *FundUpsert {
	u.SetExcluded(fund.FieldIsDefault)
	return u
}

// SetStatus sets the "status" field.
func (u *FundUpsert) SetStatus(v fund.Status) *FundUpsert {
	u.Set(fund.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FundUpsert) UpdateStatus() *FundUpsert {
	u.SetExcluded(fund.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Fund.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(fund.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FundUpsertOne) UpdateNewValues() *FundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(fund.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(fund.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(fund.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Fund.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FundUpsertOne) Ignore() *FundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FundUpsertOne) DoNothing() *FundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FundCreate.OnConflict
// documentation for more info.
func (u *FundUpsertOne) Update(set func(*FundUpsert)) *FundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FundUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FundUpsertOne) SetUpdatedAt(v time.Time) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateUpdatedAt() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *FundUpsertOne) SetMetadata(v map[string]interface{}) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateMetadata() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *FundUpsertOne) ClearMetadata() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearMetadata()
	})
}

// SetCode sets the "code" field.
func (u *FundUpsertOne) SetCode(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *FundUpsertOne) SetName(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateName() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *FundUpsertOne) SetKind(v fund.Kind) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateKind() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateKind()
	})
}

// SetTreasuryBankAccountID sets the "treasury_bank_account_id" field.
func (u *FundUpsertOne) SetTreasuryBankAccountID(v uuid.UUID) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetTreasuryBankAccountID(v)
	})
}

// UpdateTreasuryBankAccountID sets the "treasury_bank_account_id" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateTreasuryBankAccountID() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateTreasuryBankAccountID()
	})
}

// ClearTreasuryBankAccountID clears the value of the "treasury_bank_account_id" field.
func (u *FundUpsertOne) ClearTreasuryBankAccountID() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearTreasuryBankAccountID()
	})
}

// SetPaybillShortcode sets the "paybill_shortcode" field.
func (u *FundUpsertOne) SetPaybillShortcode(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetPaybillShortcode(v)
	})
}

// UpdatePaybillShortcode sets the "paybill_shortcode" field to the value that was provided on create.
func (u *FundUpsertOne) UpdatePaybillShortcode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdatePaybillShortcode()
	})
}

// ClearPaybillShortcode clears the value of the "paybill_shortcode" field.
func (u *FundUpsertOne) ClearPaybillShortcode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearPaybillShortcode()
	})
}

// SetAccountPrefix sets the "account_prefix" field.
func (u *FundUpsertOne) SetAccountPrefix(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetAccountPrefix(v)
	})
}

// UpdateAccountPrefix sets the "account_prefix" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateAccountPrefix() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateAccountPrefix()
	})
}

// ClearAccountPrefix clears the value of the "account_prefix" field.
func (u *FundUpsertOne) ClearAccountPrefix() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearAccountPrefix()
	})
}

// SetCostCenterCode sets the "cost_center_code" field.
func (u *FundUpsertOne) SetCostCenterCode(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetCostCenterCode(v)
	})
}

// UpdateCostCenterCode sets the "cost_center_code" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateCostCenterCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateCostCenterCode()
	})
}

// ClearCostCenterCode clears the value of the "cost_center_code" field.
func (u *FundUpsertOne) ClearCostCenterCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearCostCenterCode()
	})
}

// SetIncomeAccountCode sets the "income_account_code" field.
func (u *FundUpsertOne) SetIncomeAccountCode(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetIncomeAccountCode(v)
	})
}

// UpdateIncomeAccountCode sets the "income_account_code" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateIncomeAccountCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateIncomeAccountCode()
	})
}

// ClearIncomeAccountCode clears the value of the "income_account_code" field.
func (u *FundUpsertOne) ClearIncomeAccountCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearIncomeAccountCode()
	})
}

// SetReceivableAccountCode sets the "receivable_account_code" field.
func (u *FundUpsertOne) SetReceivableAccountCode(v string) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetReceivableAccountCode(v)
	})
}

// UpdateReceivableAccountCode sets the "receivable_account_code" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateReceivableAccountCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateReceivableAccountCode()
	})
}

// ClearReceivableAccountCode clears the value of the "receivable_account_code" field.
func (u *FundUpsertOne) ClearReceivableAccountCode() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.ClearReceivableAccountCode()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *FundUpsertOne) SetIsDefault(v bool) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateIsDefault() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateIsDefault()
	})
}

// SetStatus sets the "status" field.
func (u *FundUpsertOne) SetStatus(v fund.Status) *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FundUpsertOne) UpdateStatus() *FundUpsertOne {
	return u.Update(func(s *FundUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *FundUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FundCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FundUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FundUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FundUpsertOne.ID is not supported by MySQL driver. Use FundUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FundUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FundCreateBulk is the builder for creating many Fund entities in bulk.
type FundCreateBulk struct {
	config
	err      error
	builders []*FundCreate
	conflict []sql.ConflictOption
}

// Save creates the Fund entities in the database.
func (_c *FundCreateBulk) Save(ctx context.Context) ([]*Fund, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Fund, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FundCreateBulk) SaveX(ctx context.Context) []*Fund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Fund.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FundUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *FundCreateBulk) OnConflict(opts ...sql.ConflictOption) *FundUpsertBulk {
	_c.conflict = opts
	return &FundUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Fund.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FundCreateBulk) OnConflictColumns(columns ...string) *FundUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FundUpsertBulk{
		create: _c,
	}
}

// FundUpsertBulk is the builder for "upsert"-ing
// a bulk of Fund nodes.
type FundUpsertBulk struct {
	create *FundCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Fund.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(fund.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FundUpsertBulk) UpdateNewValues() *FundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(fund.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(fund.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(fund.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Fund.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FundUpsertBulk) Ignore() *FundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FundUpsertBulk) DoNothing() *FundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FundCreateBulk.OnConflict
// documentation for more info.
func (u *FundUpsertBulk) Update(set func(*FundUpsert)) *FundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FundUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FundUpsertBulk) SetUpdatedAt(v time.Time) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateUpdatedAt() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *FundUpsertBulk) SetMetadata(v map[string]interface{}) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateMetadata() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *FundUpsertBulk) ClearMetadata() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearMetadata()
	})
}

// SetCode sets the "code" field.
func (u *FundUpsertBulk) SetCode(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *FundUpsertBulk) SetName(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateName() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *FundUpsertBulk) SetKind(v fund.Kind) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateKind() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateKind()
	})
}

// SetTreasuryBankAccountID sets the "treasury_bank_account_id" field.
func (u *FundUpsertBulk) SetTreasuryBankAccountID(v uuid.UUID) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetTreasuryBankAccountID(v)
	})
}

// UpdateTreasuryBankAccountID sets the "treasury_bank_account_id" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateTreasuryBankAccountID() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateTreasuryBankAccountID()
	})
}

// ClearTreasuryBankAccountID clears the value of the "treasury_bank_account_id" field.
func (u *FundUpsertBulk) ClearTreasuryBankAccountID() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearTreasuryBankAccountID()
	})
}

// SetPaybillShortcode sets the "paybill_shortcode" field.
func (u *FundUpsertBulk) SetPaybillShortcode(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetPaybillShortcode(v)
	})
}

// UpdatePaybillShortcode sets the "paybill_shortcode" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdatePaybillShortcode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdatePaybillShortcode()
	})
}

// ClearPaybillShortcode clears the value of the "paybill_shortcode" field.
func (u *FundUpsertBulk) ClearPaybillShortcode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearPaybillShortcode()
	})
}

// SetAccountPrefix sets the "account_prefix" field.
func (u *FundUpsertBulk) SetAccountPrefix(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetAccountPrefix(v)
	})
}

// UpdateAccountPrefix sets the "account_prefix" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateAccountPrefix() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateAccountPrefix()
	})
}

// ClearAccountPrefix clears the value of the "account_prefix" field.
func (u *FundUpsertBulk) ClearAccountPrefix() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearAccountPrefix()
	})
}

// SetCostCenterCode sets the "cost_center_code" field.
func (u *FundUpsertBulk) SetCostCenterCode(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetCostCenterCode(v)
	})
}

// UpdateCostCenterCode sets the "cost_center_code" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateCostCenterCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateCostCenterCode()
	})
}

// ClearCostCenterCode clears the value of the "cost_center_code" field.
func (u *FundUpsertBulk) ClearCostCenterCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearCostCenterCode()
	})
}

// SetIncomeAccountCode sets the "income_account_code" field.
func (u *FundUpsertBulk) SetIncomeAccountCode(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetIncomeAccountCode(v)
	})
}

// UpdateIncomeAccountCode sets the "income_account_code" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateIncomeAccountCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateIncomeAccountCode()
	})
}

// ClearIncomeAccountCode clears the value of the "income_account_code" field.
func (u *FundUpsertBulk) ClearIncomeAccountCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearIncomeAccountCode()
	})
}

// SetReceivableAccountCode sets the "receivable_account_code" field.
func (u *FundUpsertBulk) SetReceivableAccountCode(v string) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetReceivableAccountCode(v)
	})
}

// UpdateReceivableAccountCode sets the "receivable_account_code" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateReceivableAccountCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateReceivableAccountCode()
	})
}

// ClearReceivableAccountCode clears the value of the "receivable_account_code" field.
func (u *FundUpsertBulk) ClearReceivableAccountCode() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.ClearReceivableAccountCode()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *FundUpsertBulk) SetIsDefault(v bool) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateIsDefault() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateIsDefault()
	})
}

// SetStatus sets the "status" field.
func (u *FundUpsertBulk) SetStatus(v fund.Status) *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FundUpsertBulk) UpdateStatus() *FundUpsertBulk {
	return u.Update(func(s *FundUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *FundUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FundCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FundCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FundUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
