// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/manualpayment"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
)

// ManualPaymentDelete is the builder for deleting a ManualPayment entity.
type ManualPaymentDelete struct {
	config
	hooks    []Hook
	mutation *ManualPaymentMutation
}

// Where appends a list predicates to the ManualPaymentDelete builder.
func (_d *ManualPaymentDelete) Where(ps ...predicate.ManualPayment) *ManualPaymentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ManualPaymentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ManualPaymentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ManualPaymentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(manualpayment.Table, sqlgraph.NewFieldSpec(manualpayment.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ManualPaymentDeleteOne is the builder for deleting a single ManualPayment entity.
type ManualPaymentDeleteOne struct {
	_d *ManualPaymentDelete
}

// Where appends a list predicates to the ManualPaymentDelete builder.
func (_d *ManualPaymentDeleteOne) Where(ps ...predicate.ManualPayment) *ManualPaymentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ManualPaymentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{manualpayment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ManualPaymentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
