// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/occurrenceentry"
	"github.com/google/uuid"
)

// OccurrenceEntryCreate is the builder for creating a OccurrenceEntry entity.
type OccurrenceEntryCreate struct {
	config
	mutation *OccurrenceEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *OccurrenceEntryCreate) SetTenantID(v uuid.UUID) *OccurrenceEntryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OccurrenceEntryCreate) SetCreatedAt(v time.Time) *OccurrenceEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillableCreatedAt(v *time.Time) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OccurrenceEntryCreate) SetUpdatedAt(v time.Time) *OccurrenceEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillableUpdatedAt(v *time.Time) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *OccurrenceEntryCreate) SetMetadata(v map[string]interface{}) *OccurrenceEntryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetPropertyID sets the "property_id" field.
func (_c *OccurrenceEntryCreate) SetPropertyID(v uuid.UUID) *OccurrenceEntryCreate {
	_c.mutation.SetPropertyID(v)
	return _c
}

// SetPostID sets the "post_id" field.
func (_c *OccurrenceEntryCreate) SetPostID(v uuid.UUID) *OccurrenceEntryCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillablePostID(v *uuid.UUID) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetPostID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *OccurrenceEntryCreate) SetKind(v occurrenceentry.Kind) *OccurrenceEntryCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillableKind(v *occurrenceentry.Kind) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *OccurrenceEntryCreate) SetBody(v string) *OccurrenceEntryCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *OccurrenceEntryCreate) SetAuthorID(v uuid.UUID) *OccurrenceEntryCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillableAuthorID(v *uuid.UUID) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetAuthorID(*v)
	}
	return _c
}

// SetAuthorKind sets the "author_kind" field.
func (_c *OccurrenceEntryCreate) SetAuthorKind(v string) *OccurrenceEntryCreate {
	_c.mutation.SetAuthorKind(v)
	return _c
}

// SetNillableAuthorKind sets the "author_kind" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillableAuthorKind(v *string) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetAuthorKind(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OccurrenceEntryCreate) SetID(v uuid.UUID) *OccurrenceEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OccurrenceEntryCreate) SetNillableID(v *uuid.UUID) *OccurrenceEntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OccurrenceEntryMutation object of the builder.
func (_c *OccurrenceEntryCreate) Mutation() *OccurrenceEntryMutation {
	return _c.mutation
}

// Save creates the OccurrenceEntry in the database.
func (_c *OccurrenceEntryCreate) Save(ctx context.Context) (*OccurrenceEntry, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OccurrenceEntryCreate) SaveX(ctx context.Context) *OccurrenceEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OccurrenceEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OccurrenceEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OccurrenceEntryCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if occurrenceentry.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized occurrenceentry.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := occurrenceentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if occurrenceentry.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized occurrenceentry.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := occurrenceentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := occurrenceentry.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if occurrenceentry.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized occurrenceentry.DefaultID (forgotten import ent/runtime?)")
		}
		v := occurrenceentry.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OccurrenceEntryCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "OccurrenceEntry.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OccurrenceEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OccurrenceEntry.updated_at"`)}
	}
	if _, ok := _c.mutation.PropertyID(); !ok {
		return &ValidationError{Name: "property_id", err: errors.New(`ent: missing required field "OccurrenceEntry.property_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "OccurrenceEntry.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := occurrenceentry.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "OccurrenceEntry.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "OccurrenceEntry.body"`)}
	}
	return nil
}

func (_c *OccurrenceEntryCreate) sqlSave(ctx context.Context) (*OccurrenceEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OccurrenceEntryCreate) createSpec() (*OccurrenceEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &OccurrenceEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(occurrenceentry.Table, sqlgraph.NewFieldSpec(occurrenceentry.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(occurrenceentry.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(occurrenceentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(occurrenceentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(occurrenceentry.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.PropertyID(); ok {
		_spec.SetField(occurrenceentry.FieldPropertyID, field.TypeUUID, value)
		_node.PropertyID = value
	}
	if value, ok := _c.mutation.PostID(); ok {
		_spec.SetField(occurrenceentry.FieldPostID, field.TypeUUID, value)
		_node.PostID = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(occurrenceentry.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(occurrenceentry.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(occurrenceentry.FieldAuthorID, field.TypeUUID, value)
		_node.AuthorID = &value
	}
	if value, ok := _c.mutation.AuthorKind(); ok {
		_spec.SetField(occurrenceentry.FieldAuthorKind, field.TypeString, value)
		_node.AuthorKind = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OccurrenceEntry.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OccurrenceEntryUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *OccurrenceEntryCreate) OnConflict(opts ...sql.ConflictOption) *OccurrenceEntryUpsertOne {
	_c.conflict = opts
	return &OccurrenceEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OccurrenceEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OccurrenceEntryCreate) OnConflictColumns(columns ...string) *OccurrenceEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OccurrenceEntryUpsertOne{
		create: _c,
	}
}

type (
	// OccurrenceEntryUpsertOne is the builder for "upsert"-ing
	//  one OccurrenceEntry node.
	OccurrenceEntryUpsertOne struct {
		create *OccurrenceEntryCreate
	}

	// OccurrenceEntryUpsert is the "OnConflict" setter.
	OccurrenceEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OccurrenceEntryUpsert) SetUpdatedAt(v time.Time) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdateUpdatedAt() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldUpdatedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *OccurrenceEntryUpsert) SetMetadata(v map[string]interface{}) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdateMetadata() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OccurrenceEntryUpsert) ClearMetadata() *OccurrenceEntryUpsert {
	u.SetNull(occurrenceentry.FieldMetadata)
	return u
}

// SetPropertyID sets the "property_id" field.
func (u *OccurrenceEntryUpsert) SetPropertyID(v uuid.UUID) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldPropertyID, v)
	return u
}

// UpdatePropertyID sets the "property_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdatePropertyID() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldPropertyID)
	return u
}

// SetPostID sets the "post_id" field.
func (u *OccurrenceEntryUpsert) SetPostID(v uuid.UUID) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdatePostID() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldPostID)
	return u
}

// ClearPostID clears the value of the "post_id" field.
func (u *OccurrenceEntryUpsert) ClearPostID() *OccurrenceEntryUpsert {
	u.SetNull(occurrenceentry.FieldPostID)
	return u
}

// SetKind sets the "kind" field.
func (u *OccurrenceEntryUpsert) SetKind(v occurrenceentry.Kind) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdateKind() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldKind)
	return u
}

// SetBody sets the "body" field.
func (u *OccurrenceEntryUpsert) SetBody(v string) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdateBody() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldBody)
	return u
}

// SetAuthorID sets the "author_id" field.
func (u *OccurrenceEntryUpsert) SetAuthorID(v uuid.UUID) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldAuthorID, v)
	return u
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdateAuthorID() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldAuthorID)
	return u
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *OccurrenceEntryUpsert) ClearAuthorID() *OccurrenceEntryUpsert {
	u.SetNull(occurrenceentry.FieldAuthorID)
	return u
}

// SetAuthorKind sets the "author_kind" field.
func (u *OccurrenceEntryUpsert) SetAuthorKind(v string) *OccurrenceEntryUpsert {
	u.Set(occurrenceentry.FieldAuthorKind, v)
	return u
}

// UpdateAuthorKind sets the "author_kind" field to the value that was provided on create.
func (u *OccurrenceEntryUpsert) UpdateAuthorKind() *OccurrenceEntryUpsert {
	u.SetExcluded(occurrenceentry.FieldAuthorKind)
	return u
}

// ClearAuthorKind clears the value of the "author_kind" field.
func (u *OccurrenceEntryUpsert) ClearAuthorKind() *OccurrenceEntryUpsert {
	u.SetNull(occurrenceentry.FieldAuthorKind)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OccurrenceEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(occurrenceentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OccurrenceEntryUpsertOne) UpdateNewValues() *OccurrenceEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(occurrenceentry.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(occurrenceentry.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(occurrenceentry.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OccurrenceEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OccurrenceEntryUpsertOne) Ignore() *OccurrenceEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OccurrenceEntryUpsertOne) DoNothing() *OccurrenceEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OccurrenceEntryCreate.OnConflict
// documentation for more info.
func (u *OccurrenceEntryUpsertOne) Update(set func(*OccurrenceEntryUpsert)) *OccurrenceEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OccurrenceEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OccurrenceEntryUpsertOne) SetUpdatedAt(v time.Time) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdateUpdatedAt() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *OccurrenceEntryUpsertOne) SetMetadata(v map[string]interface{}) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdateMetadata() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OccurrenceEntryUpsertOne) ClearMetadata() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearMetadata()
	})
}

// SetPropertyID sets the "property_id" field.
func (u *OccurrenceEntryUpsertOne) SetPropertyID(v uuid.UUID) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetPropertyID(v)
	})
}

// UpdatePropertyID sets the "property_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdatePropertyID() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdatePropertyID()
	})
}

// SetPostID sets the "post_id" field.
func (u *OccurrenceEntryUpsertOne) SetPostID(v uuid.UUID) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdatePostID() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdatePostID()
	})
}

// ClearPostID clears the value of the "post_id" field.
func (u *OccurrenceEntryUpsertOne) ClearPostID() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearPostID()
	})
}

// SetKind sets the "kind" field.
func (u *OccurrenceEntryUpsertOne) SetKind(v occurrenceentry.Kind) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdateKind() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateKind()
	})
}

// SetBody sets the "body" field.
func (u *OccurrenceEntryUpsertOne) SetBody(v string) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdateBody() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateBody()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *OccurrenceEntryUpsertOne) SetAuthorID(v uuid.UUID) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdateAuthorID() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateAuthorID()
	})
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *OccurrenceEntryUpsertOne) ClearAuthorID() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearAuthorID()
	})
}

// SetAuthorKind sets the "author_kind" field.
func (u *OccurrenceEntryUpsertOne) SetAuthorKind(v string) *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetAuthorKind(v)
	})
}

// UpdateAuthorKind sets the "author_kind" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertOne) UpdateAuthorKind() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateAuthorKind()
	})
}

// ClearAuthorKind clears the value of the "author_kind" field.
func (u *OccurrenceEntryUpsertOne) ClearAuthorKind() *OccurrenceEntryUpsertOne {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearAuthorKind()
	})
}

// Exec executes the query.
func (u *OccurrenceEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OccurrenceEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OccurrenceEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OccurrenceEntryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OccurrenceEntryUpsertOne.ID is not supported by MySQL driver. Use OccurrenceEntryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OccurrenceEntryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OccurrenceEntryCreateBulk is the builder for creating many OccurrenceEntry entities in bulk.
type OccurrenceEntryCreateBulk struct {
	config
	err      error
	builders []*OccurrenceEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the OccurrenceEntry entities in the database.
func (_c *OccurrenceEntryCreateBulk) Save(ctx context.Context) ([]*OccurrenceEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OccurrenceEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OccurrenceEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OccurrenceEntryCreateBulk) SaveX(ctx context.Context) []*OccurrenceEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OccurrenceEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OccurrenceEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OccurrenceEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OccurrenceEntryUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *OccurrenceEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *OccurrenceEntryUpsertBulk {
	_c.conflict = opts
	return &OccurrenceEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OccurrenceEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OccurrenceEntryCreateBulk) OnConflictColumns(columns ...string) *OccurrenceEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OccurrenceEntryUpsertBulk{
		create: _c,
	}
}

// OccurrenceEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of OccurrenceEntry nodes.
type OccurrenceEntryUpsertBulk struct {
	create *OccurrenceEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OccurrenceEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(occurrenceentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OccurrenceEntryUpsertBulk) UpdateNewValues() *OccurrenceEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(occurrenceentry.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(occurrenceentry.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(occurrenceentry.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OccurrenceEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OccurrenceEntryUpsertBulk) Ignore() *OccurrenceEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OccurrenceEntryUpsertBulk) DoNothing() *OccurrenceEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OccurrenceEntryCreateBulk.OnConflict
// documentation for more info.
func (u *OccurrenceEntryUpsertBulk) Update(set func(*OccurrenceEntryUpsert)) *OccurrenceEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OccurrenceEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OccurrenceEntryUpsertBulk) SetUpdatedAt(v time.Time) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdateUpdatedAt() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *OccurrenceEntryUpsertBulk) SetMetadata(v map[string]interface{}) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdateMetadata() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OccurrenceEntryUpsertBulk) ClearMetadata() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearMetadata()
	})
}

// SetPropertyID sets the "property_id" field.
func (u *OccurrenceEntryUpsertBulk) SetPropertyID(v uuid.UUID) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetPropertyID(v)
	})
}

// UpdatePropertyID sets the "property_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdatePropertyID() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdatePropertyID()
	})
}

// SetPostID sets the "post_id" field.
func (u *OccurrenceEntryUpsertBulk) SetPostID(v uuid.UUID) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdatePostID() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdatePostID()
	})
}

// ClearPostID clears the value of the "post_id" field.
func (u *OccurrenceEntryUpsertBulk) ClearPostID() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearPostID()
	})
}

// SetKind sets the "kind" field.
func (u *OccurrenceEntryUpsertBulk) SetKind(v occurrenceentry.Kind) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdateKind() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateKind()
	})
}

// SetBody sets the "body" field.
func (u *OccurrenceEntryUpsertBulk) SetBody(v string) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdateBody() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateBody()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *OccurrenceEntryUpsertBulk) SetAuthorID(v uuid.UUID) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdateAuthorID() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateAuthorID()
	})
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *OccurrenceEntryUpsertBulk) ClearAuthorID() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearAuthorID()
	})
}

// SetAuthorKind sets the "author_kind" field.
func (u *OccurrenceEntryUpsertBulk) SetAuthorKind(v string) *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.SetAuthorKind(v)
	})
}

// UpdateAuthorKind sets the "author_kind" field to the value that was provided on create.
func (u *OccurrenceEntryUpsertBulk) UpdateAuthorKind() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.UpdateAuthorKind()
	})
}

// ClearAuthorKind clears the value of the "author_kind" field.
func (u *OccurrenceEntryUpsertBulk) ClearAuthorKind() *OccurrenceEntryUpsertBulk {
	return u.Update(func(s *OccurrenceEntryUpsert) {
		s.ClearAuthorKind()
	})
}

// Exec executes the query.
func (u *OccurrenceEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OccurrenceEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OccurrenceEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OccurrenceEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
