// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/maskani-api/internal/ent/privacyrequest"
	"github.com/google/uuid"
)

// PrivacyRequest is the model entity for the PrivacyRequest schema.
type PrivacyRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// PartyID holds the value of the "party_id" field.
	PartyID *uuid.UUID `json:"party_id,omitempty"`
	// RequesterName holds the value of the "requester_name" field.
	RequesterName string `json:"requester_name,omitempty"`
	// RequesterPhone holds the value of the "requester_phone" field.
	RequesterPhone string `json:"requester_phone,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind privacyrequest.Kind `json:"kind,omitempty"`
	// Status holds the value of the "status" field.
	Status privacyrequest.Status `json:"status,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// DueAt holds the value of the "due_at" field.
	DueAt time.Time `json:"due_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ExportFileKey holds the value of the "export_file_key" field.
	ExportFileKey string `json:"export_file_key,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PrivacyRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case privacyrequest.FieldPartyID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case privacyrequest.FieldMetadata:
			values[i] = new([]byte)
		case privacyrequest.FieldRequesterName, privacyrequest.FieldRequesterPhone, privacyrequest.FieldKind, privacyrequest.FieldStatus, privacyrequest.FieldExportFileKey, privacyrequest.FieldNotes:
			values[i] = new(sql.NullString)
		case privacyrequest.FieldCreatedAt, privacyrequest.FieldUpdatedAt, privacyrequest.FieldReceivedAt, privacyrequest.FieldDueAt, privacyrequest.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case privacyrequest.FieldID, privacyrequest.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PrivacyRequest fields.
func (_m *PrivacyRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case privacyrequest.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case privacyrequest.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case privacyrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case privacyrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case privacyrequest.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case privacyrequest.FieldPartyID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field party_id", values[i])
			} else if value.Valid {
				_m.PartyID = new(uuid.UUID)
				*_m.PartyID = *value.S.(*uuid.UUID)
			}
		case privacyrequest.FieldRequesterName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requester_name", values[i])
			} else if value.Valid {
				_m.RequesterName = value.String
			}
		case privacyrequest.FieldRequesterPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requester_phone", values[i])
			} else if value.Valid {
				_m.RequesterPhone = value.String
			}
		case privacyrequest.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = privacyrequest.Kind(value.String)
			}
		case privacyrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = privacyrequest.Status(value.String)
			}
		case privacyrequest.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case privacyrequest.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_at", values[i])
			} else if value.Valid {
				_m.DueAt = value.Time
			}
		case privacyrequest.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case privacyrequest.FieldExportFileKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field export_file_key", values[i])
			} else if value.Valid {
				_m.ExportFileKey = value.String
			}
		case privacyrequest.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PrivacyRequest.
// This includes values selected through modifiers, order, etc.
func (_m *PrivacyRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PrivacyRequest.
// Note that you need to call PrivacyRequest.Unwrap() before calling this method if this PrivacyRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PrivacyRequest) Update() *PrivacyRequestUpdateOne {
	return NewPrivacyRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PrivacyRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PrivacyRequest) Unwrap() *PrivacyRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PrivacyRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PrivacyRequest) String() string {
	var builder strings.Builder
	builder.WriteString("PrivacyRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.PartyID; v != nil {
		builder.WriteString("party_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("requester_name=")
	builder.WriteString(_m.RequesterName)
	builder.WriteString(", ")
	builder.WriteString("requester_phone=")
	builder.WriteString(_m.RequesterPhone)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("due_at=")
	builder.WriteString(_m.DueAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("export_file_key=")
	builder.WriteString(_m.ExportFileKey)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// PrivacyRequests is a parsable slice of PrivacyRequest.
type PrivacyRequests []*PrivacyRequest
