// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/fund"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
	"github.com/bengobox/maskani-api/internal/ent/unit"
	"github.com/bengobox/maskani-api/internal/ent/unitaccount"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// UnitAccountUpdate is the builder for updating UnitAccount entities.
type UnitAccountUpdate struct {
	config
	hooks     []Hook
	mutation  *UnitAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UnitAccountUpdate builder.
func (_u *UnitAccountUpdate) Where(ps ...predicate.UnitAccount) *UnitAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UnitAccountUpdate) SetUpdatedAt(v time.Time) *UnitAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UnitAccountUpdate) SetMetadata(v map[string]interface{}) *UnitAccountUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UnitAccountUpdate) ClearMetadata() *UnitAccountUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUnitID sets the "unit_id" field.
func (_u *UnitAccountUpdate) SetUnitID(v uuid.UUID) *UnitAccountUpdate {
	_u.mutation.SetUnitID(v)
	return _u
}

// SetNillableUnitID sets the "unit_id" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableUnitID(v *uuid.UUID) *UnitAccountUpdate {
	if v != nil {
		_u.SetUnitID(*v)
	}
	return _u
}

// SetFundID sets the "fund_id" field.
func (_u *UnitAccountUpdate) SetFundID(v uuid.UUID) *UnitAccountUpdate {
	_u.mutation.SetFundID(v)
	return _u
}

// SetNillableFundID sets the "fund_id" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableFundID(v *uuid.UUID) *UnitAccountUpdate {
	if v != nil {
		_u.SetFundID(*v)
	}
	return _u
}

// SetAccountRef sets the "account_ref" field.
func (_u *UnitAccountUpdate) SetAccountRef(v string) *UnitAccountUpdate {
	_u.mutation.SetAccountRef(v)
	return _u
}

// SetNillableAccountRef sets the "account_ref" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableAccountRef(v *string) *UnitAccountUpdate {
	if v != nil {
		_u.SetAccountRef(*v)
	}
	return _u
}

// SetPrimaryPartyID sets the "primary_party_id" field.
func (_u *UnitAccountUpdate) SetPrimaryPartyID(v uuid.UUID) *UnitAccountUpdate {
	_u.mutation.SetPrimaryPartyID(v)
	return _u
}

// SetNillablePrimaryPartyID sets the "primary_party_id" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillablePrimaryPartyID(v *uuid.UUID) *UnitAccountUpdate {
	if v != nil {
		_u.SetPrimaryPartyID(*v)
	}
	return _u
}

// ClearPrimaryPartyID clears the value of the "primary_party_id" field.
func (_u *UnitAccountUpdate) ClearPrimaryPartyID() *UnitAccountUpdate {
	_u.mutation.ClearPrimaryPartyID()
	return _u
}

// SetCustomerName sets the "customer_name" field.
func (_u *UnitAccountUpdate) SetCustomerName(v string) *UnitAccountUpdate {
	_u.mutation.SetCustomerName(v)
	return _u
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableCustomerName(v *string) *UnitAccountUpdate {
	if v != nil {
		_u.SetCustomerName(*v)
	}
	return _u
}

// ClearCustomerName clears the value of the "customer_name" field.
func (_u *UnitAccountUpdate) ClearCustomerName() *UnitAccountUpdate {
	_u.mutation.ClearCustomerName()
	return _u
}

// SetCustomerPhone sets the "customer_phone" field.
func (_u *UnitAccountUpdate) SetCustomerPhone(v string) *UnitAccountUpdate {
	_u.mutation.SetCustomerPhone(v)
	return _u
}

// SetNillableCustomerPhone sets the "customer_phone" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableCustomerPhone(v *string) *UnitAccountUpdate {
	if v != nil {
		_u.SetCustomerPhone(*v)
	}
	return _u
}

// ClearCustomerPhone clears the value of the "customer_phone" field.
func (_u *UnitAccountUpdate) ClearCustomerPhone() *UnitAccountUpdate {
	_u.mutation.ClearCustomerPhone()
	return _u
}

// SetC2bRouteRegisteredAt sets the "c2b_route_registered_at" field.
func (_u *UnitAccountUpdate) SetC2bRouteRegisteredAt(v time.Time) *UnitAccountUpdate {
	_u.mutation.SetC2bRouteRegisteredAt(v)
	return _u
}

// SetNillableC2bRouteRegisteredAt sets the "c2b_route_registered_at" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableC2bRouteRegisteredAt(v *time.Time) *UnitAccountUpdate {
	if v != nil {
		_u.SetC2bRouteRegisteredAt(*v)
	}
	return _u
}

// ClearC2bRouteRegisteredAt clears the value of the "c2b_route_registered_at" field.
func (_u *UnitAccountUpdate) ClearC2bRouteRegisteredAt() *UnitAccountUpdate {
	_u.mutation.ClearC2bRouteRegisteredAt()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UnitAccountUpdate) SetBalance(v decimal.Decimal) *UnitAccountUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableBalance(v *decimal.Decimal) *UnitAccountUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UnitAccountUpdate) AddBalance(v decimal.Decimal) *UnitAccountUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetOpeningBalance sets the "opening_balance" field.
func (_u *UnitAccountUpdate) SetOpeningBalance(v decimal.Decimal) *UnitAccountUpdate {
	_u.mutation.ResetOpeningBalance()
	_u.mutation.SetOpeningBalance(v)
	return _u
}

// SetNillableOpeningBalance sets the "opening_balance" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableOpeningBalance(v *decimal.Decimal) *UnitAccountUpdate {
	if v != nil {
		_u.SetOpeningBalance(*v)
	}
	return _u
}

// AddOpeningBalance adds value to the "opening_balance" field.
func (_u *UnitAccountUpdate) AddOpeningBalance(v decimal.Decimal) *UnitAccountUpdate {
	_u.mutation.AddOpeningBalance(v)
	return _u
}

// SetBalanceSyncedAt sets the "balance_synced_at" field.
func (_u *UnitAccountUpdate) SetBalanceSyncedAt(v time.Time) *UnitAccountUpdate {
	_u.mutation.SetBalanceSyncedAt(v)
	return _u
}

// SetNillableBalanceSyncedAt sets the "balance_synced_at" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableBalanceSyncedAt(v *time.Time) *UnitAccountUpdate {
	if v != nil {
		_u.SetBalanceSyncedAt(*v)
	}
	return _u
}

// ClearBalanceSyncedAt clears the value of the "balance_synced_at" field.
func (_u *UnitAccountUpdate) ClearBalanceSyncedAt() *UnitAccountUpdate {
	_u.mutation.ClearBalanceSyncedAt()
	return _u
}

// SetLastPaymentAt sets the "last_payment_at" field.
func (_u *UnitAccountUpdate) SetLastPaymentAt(v time.Time) *UnitAccountUpdate {
	_u.mutation.SetLastPaymentAt(v)
	return _u
}

// SetNillableLastPaymentAt sets the "last_payment_at" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableLastPaymentAt(v *time.Time) *UnitAccountUpdate {
	if v != nil {
		_u.SetLastPaymentAt(*v)
	}
	return _u
}

// ClearLastPaymentAt clears the value of the "last_payment_at" field.
func (_u *UnitAccountUpdate) ClearLastPaymentAt() *UnitAccountUpdate {
	_u.mutation.ClearLastPaymentAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UnitAccountUpdate) SetStatus(v unitaccount.Status) *UnitAccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UnitAccountUpdate) SetNillableStatus(v *unitaccount.Status) *UnitAccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUnit sets the "unit" edge to the Unit entity.
func (_u *UnitAccountUpdate) SetUnit(v *Unit) *UnitAccountUpdate {
	return _u.SetUnitID(v.ID)
}

// SetFund sets the "fund" edge to the Fund entity.
func (_u *UnitAccountUpdate) SetFund(v *Fund) *UnitAccountUpdate {
	return _u.SetFundID(v.ID)
}

// Mutation returns the UnitAccountMutation object of the builder.
func (_u *UnitAccountUpdate) Mutation() *UnitAccountMutation {
	return _u.mutation
}

// ClearUnit clears the "unit" edge to the Unit entity.
func (_u *UnitAccountUpdate) ClearUnit() *UnitAccountUpdate {
	_u.mutation.ClearUnit()
	return _u
}

// ClearFund clears the "fund" edge to the Fund entity.
func (_u *UnitAccountUpdate) ClearFund() *UnitAccountUpdate {
	_u.mutation.ClearFund()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnitAccountUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnitAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnitAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnitAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UnitAccountUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if unitaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized unitaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := unitaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnitAccountUpdate) check() error {
	if v, ok := _u.mutation.AccountRef(); ok {
		if err := unitaccount.AccountRefValidator(v); err != nil {
			return &ValidationError{Name: "account_ref", err: fmt.Errorf(`ent: validator failed for field "UnitAccount.account_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := unitaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UnitAccount.status": %w`, err)}
		}
	}
	if _u.mutation.UnitCleared() && len(_u.mutation.UnitIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UnitAccount.unit"`)
	}
	if _u.mutation.FundCleared() && len(_u.mutation.FundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UnitAccount.fund"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UnitAccountUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UnitAccountUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UnitAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unitaccount.Table, unitaccount.Columns, sqlgraph.NewFieldSpec(unitaccount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(unitaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(unitaccount.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(unitaccount.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.AccountRef(); ok {
		_spec.SetField(unitaccount.FieldAccountRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrimaryPartyID(); ok {
		_spec.SetField(unitaccount.FieldPrimaryPartyID, field.TypeUUID, value)
	}
	if _u.mutation.PrimaryPartyIDCleared() {
		_spec.ClearField(unitaccount.FieldPrimaryPartyID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CustomerName(); ok {
		_spec.SetField(unitaccount.FieldCustomerName, field.TypeString, value)
	}
	if _u.mutation.CustomerNameCleared() {
		_spec.ClearField(unitaccount.FieldCustomerName, field.TypeString)
	}
	if value, ok := _u.mutation.CustomerPhone(); ok {
		_spec.SetField(unitaccount.FieldCustomerPhone, field.TypeString, value)
	}
	if _u.mutation.CustomerPhoneCleared() {
		_spec.ClearField(unitaccount.FieldCustomerPhone, field.TypeString)
	}
	if value, ok := _u.mutation.C2bRouteRegisteredAt(); ok {
		_spec.SetField(unitaccount.FieldC2bRouteRegisteredAt, field.TypeTime, value)
	}
	if _u.mutation.C2bRouteRegisteredAtCleared() {
		_spec.ClearField(unitaccount.FieldC2bRouteRegisteredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(unitaccount.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(unitaccount.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OpeningBalance(); ok {
		_spec.SetField(unitaccount.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOpeningBalance(); ok {
		_spec.AddField(unitaccount.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceSyncedAt(); ok {
		_spec.SetField(unitaccount.FieldBalanceSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.BalanceSyncedAtCleared() {
		_spec.ClearField(unitaccount.FieldBalanceSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPaymentAt(); ok {
		_spec.SetField(unitaccount.FieldLastPaymentAt, field.TypeTime, value)
	}
	if _u.mutation.LastPaymentAtCleared() {
		_spec.ClearField(unitaccount.FieldLastPaymentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(unitaccount.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.UnitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.UnitTable,
			Columns: []string{unitaccount.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.UnitTable,
			Columns: []string{unitaccount.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.FundTable,
			Columns: []string{unitaccount.FundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fund.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.FundTable,
			Columns: []string{unitaccount.FundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fund.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unitaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnitAccountUpdateOne is the builder for updating a single UnitAccount entity.
type UnitAccountUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UnitAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UnitAccountUpdateOne) SetUpdatedAt(v time.Time) *UnitAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UnitAccountUpdateOne) SetMetadata(v map[string]interface{}) *UnitAccountUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UnitAccountUpdateOne) ClearMetadata() *UnitAccountUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUnitID sets the "unit_id" field.
func (_u *UnitAccountUpdateOne) SetUnitID(v uuid.UUID) *UnitAccountUpdateOne {
	_u.mutation.SetUnitID(v)
	return _u
}

// SetNillableUnitID sets the "unit_id" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableUnitID(v *uuid.UUID) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetUnitID(*v)
	}
	return _u
}

// SetFundID sets the "fund_id" field.
func (_u *UnitAccountUpdateOne) SetFundID(v uuid.UUID) *UnitAccountUpdateOne {
	_u.mutation.SetFundID(v)
	return _u
}

// SetNillableFundID sets the "fund_id" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableFundID(v *uuid.UUID) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetFundID(*v)
	}
	return _u
}

// SetAccountRef sets the "account_ref" field.
func (_u *UnitAccountUpdateOne) SetAccountRef(v string) *UnitAccountUpdateOne {
	_u.mutation.SetAccountRef(v)
	return _u
}

// SetNillableAccountRef sets the "account_ref" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableAccountRef(v *string) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetAccountRef(*v)
	}
	return _u
}

// SetPrimaryPartyID sets the "primary_party_id" field.
func (_u *UnitAccountUpdateOne) SetPrimaryPartyID(v uuid.UUID) *UnitAccountUpdateOne {
	_u.mutation.SetPrimaryPartyID(v)
	return _u
}

// SetNillablePrimaryPartyID sets the "primary_party_id" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillablePrimaryPartyID(v *uuid.UUID) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetPrimaryPartyID(*v)
	}
	return _u
}

// ClearPrimaryPartyID clears the value of the "primary_party_id" field.
func (_u *UnitAccountUpdateOne) ClearPrimaryPartyID() *UnitAccountUpdateOne {
	_u.mutation.ClearPrimaryPartyID()
	return _u
}

// SetCustomerName sets the "customer_name" field.
func (_u *UnitAccountUpdateOne) SetCustomerName(v string) *UnitAccountUpdateOne {
	_u.mutation.SetCustomerName(v)
	return _u
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableCustomerName(v *string) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetCustomerName(*v)
	}
	return _u
}

// ClearCustomerName clears the value of the "customer_name" field.
func (_u *UnitAccountUpdateOne) ClearCustomerName() *UnitAccountUpdateOne {
	_u.mutation.ClearCustomerName()
	return _u
}

// SetCustomerPhone sets the "customer_phone" field.
func (_u *UnitAccountUpdateOne) SetCustomerPhone(v string) *UnitAccountUpdateOne {
	_u.mutation.SetCustomerPhone(v)
	return _u
}

// SetNillableCustomerPhone sets the "customer_phone" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableCustomerPhone(v *string) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetCustomerPhone(*v)
	}
	return _u
}

// ClearCustomerPhone clears the value of the "customer_phone" field.
func (_u *UnitAccountUpdateOne) ClearCustomerPhone() *UnitAccountUpdateOne {
	_u.mutation.ClearCustomerPhone()
	return _u
}

// SetC2bRouteRegisteredAt sets the "c2b_route_registered_at" field.
func (_u *UnitAccountUpdateOne) SetC2bRouteRegisteredAt(v time.Time) *UnitAccountUpdateOne {
	_u.mutation.SetC2bRouteRegisteredAt(v)
	return _u
}

// SetNillableC2bRouteRegisteredAt sets the "c2b_route_registered_at" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableC2bRouteRegisteredAt(v *time.Time) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetC2bRouteRegisteredAt(*v)
	}
	return _u
}

// ClearC2bRouteRegisteredAt clears the value of the "c2b_route_registered_at" field.
func (_u *UnitAccountUpdateOne) ClearC2bRouteRegisteredAt() *UnitAccountUpdateOne {
	_u.mutation.ClearC2bRouteRegisteredAt()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UnitAccountUpdateOne) SetBalance(v decimal.Decimal) *UnitAccountUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableBalance(v *decimal.Decimal) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UnitAccountUpdateOne) AddBalance(v decimal.Decimal) *UnitAccountUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetOpeningBalance sets the "opening_balance" field.
func (_u *UnitAccountUpdateOne) SetOpeningBalance(v decimal.Decimal) *UnitAccountUpdateOne {
	_u.mutation.ResetOpeningBalance()
	_u.mutation.SetOpeningBalance(v)
	return _u
}

// SetNillableOpeningBalance sets the "opening_balance" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableOpeningBalance(v *decimal.Decimal) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetOpeningBalance(*v)
	}
	return _u
}

// AddOpeningBalance adds value to the "opening_balance" field.
func (_u *UnitAccountUpdateOne) AddOpeningBalance(v decimal.Decimal) *UnitAccountUpdateOne {
	_u.mutation.AddOpeningBalance(v)
	return _u
}

// SetBalanceSyncedAt sets the "balance_synced_at" field.
func (_u *UnitAccountUpdateOne) SetBalanceSyncedAt(v time.Time) *UnitAccountUpdateOne {
	_u.mutation.SetBalanceSyncedAt(v)
	return _u
}

// SetNillableBalanceSyncedAt sets the "balance_synced_at" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableBalanceSyncedAt(v *time.Time) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetBalanceSyncedAt(*v)
	}
	return _u
}

// ClearBalanceSyncedAt clears the value of the "balance_synced_at" field.
func (_u *UnitAccountUpdateOne) ClearBalanceSyncedAt() *UnitAccountUpdateOne {
	_u.mutation.ClearBalanceSyncedAt()
	return _u
}

// SetLastPaymentAt sets the "last_payment_at" field.
func (_u *UnitAccountUpdateOne) SetLastPaymentAt(v time.Time) *UnitAccountUpdateOne {
	_u.mutation.SetLastPaymentAt(v)
	return _u
}

// SetNillableLastPaymentAt sets the "last_payment_at" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableLastPaymentAt(v *time.Time) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetLastPaymentAt(*v)
	}
	return _u
}

// ClearLastPaymentAt clears the value of the "last_payment_at" field.
func (_u *UnitAccountUpdateOne) ClearLastPaymentAt() *UnitAccountUpdateOne {
	_u.mutation.ClearLastPaymentAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UnitAccountUpdateOne) SetStatus(v unitaccount.Status) *UnitAccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UnitAccountUpdateOne) SetNillableStatus(v *unitaccount.Status) *UnitAccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUnit sets the "unit" edge to the Unit entity.
func (_u *UnitAccountUpdateOne) SetUnit(v *Unit) *UnitAccountUpdateOne {
	return _u.SetUnitID(v.ID)
}

// SetFund sets the "fund" edge to the Fund entity.
func (_u *UnitAccountUpdateOne) SetFund(v *Fund) *UnitAccountUpdateOne {
	return _u.SetFundID(v.ID)
}

// Mutation returns the UnitAccountMutation object of the builder.
func (_u *UnitAccountUpdateOne) Mutation() *UnitAccountMutation {
	return _u.mutation
}

// ClearUnit clears the "unit" edge to the Unit entity.
func (_u *UnitAccountUpdateOne) ClearUnit() *UnitAccountUpdateOne {
	_u.mutation.ClearUnit()
	return _u
}

// ClearFund clears the "fund" edge to the Fund entity.
func (_u *UnitAccountUpdateOne) ClearFund() *UnitAccountUpdateOne {
	_u.mutation.ClearFund()
	return _u
}

// Where appends a list predicates to the UnitAccountUpdate builder.
func (_u *UnitAccountUpdateOne) Where(ps ...predicate.UnitAccount) *UnitAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnitAccountUpdateOne) Select(field string, fields ...string) *UnitAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UnitAccount entity.
func (_u *UnitAccountUpdateOne) Save(ctx context.Context) (*UnitAccount, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnitAccountUpdateOne) SaveX(ctx context.Context) *UnitAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnitAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnitAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UnitAccountUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if unitaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized unitaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := unitaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnitAccountUpdateOne) check() error {
	if v, ok := _u.mutation.AccountRef(); ok {
		if err := unitaccount.AccountRefValidator(v); err != nil {
			return &ValidationError{Name: "account_ref", err: fmt.Errorf(`ent: validator failed for field "UnitAccount.account_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := unitaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UnitAccount.status": %w`, err)}
		}
	}
	if _u.mutation.UnitCleared() && len(_u.mutation.UnitIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UnitAccount.unit"`)
	}
	if _u.mutation.FundCleared() && len(_u.mutation.FundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UnitAccount.fund"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UnitAccountUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UnitAccountUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UnitAccountUpdateOne) sqlSave(ctx context.Context) (_node *UnitAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unitaccount.Table, unitaccount.Columns, sqlgraph.NewFieldSpec(unitaccount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UnitAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unitaccount.FieldID)
		for _, f := range fields {
			if !unitaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unitaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(unitaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(unitaccount.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(unitaccount.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.AccountRef(); ok {
		_spec.SetField(unitaccount.FieldAccountRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrimaryPartyID(); ok {
		_spec.SetField(unitaccount.FieldPrimaryPartyID, field.TypeUUID, value)
	}
	if _u.mutation.PrimaryPartyIDCleared() {
		_spec.ClearField(unitaccount.FieldPrimaryPartyID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CustomerName(); ok {
		_spec.SetField(unitaccount.FieldCustomerName, field.TypeString, value)
	}
	if _u.mutation.CustomerNameCleared() {
		_spec.ClearField(unitaccount.FieldCustomerName, field.TypeString)
	}
	if value, ok := _u.mutation.CustomerPhone(); ok {
		_spec.SetField(unitaccount.FieldCustomerPhone, field.TypeString, value)
	}
	if _u.mutation.CustomerPhoneCleared() {
		_spec.ClearField(unitaccount.FieldCustomerPhone, field.TypeString)
	}
	if value, ok := _u.mutation.C2bRouteRegisteredAt(); ok {
		_spec.SetField(unitaccount.FieldC2bRouteRegisteredAt, field.TypeTime, value)
	}
	if _u.mutation.C2bRouteRegisteredAtCleared() {
		_spec.ClearField(unitaccount.FieldC2bRouteRegisteredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(unitaccount.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(unitaccount.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OpeningBalance(); ok {
		_spec.SetField(unitaccount.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOpeningBalance(); ok {
		_spec.AddField(unitaccount.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceSyncedAt(); ok {
		_spec.SetField(unitaccount.FieldBalanceSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.BalanceSyncedAtCleared() {
		_spec.ClearField(unitaccount.FieldBalanceSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPaymentAt(); ok {
		_spec.SetField(unitaccount.FieldLastPaymentAt, field.TypeTime, value)
	}
	if _u.mutation.LastPaymentAtCleared() {
		_spec.ClearField(unitaccount.FieldLastPaymentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(unitaccount.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.UnitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.UnitTable,
			Columns: []string{unitaccount.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.UnitTable,
			Columns: []string{unitaccount.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.FundTable,
			Columns: []string{unitaccount.FundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fund.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unitaccount.FundTable,
			Columns: []string{unitaccount.FundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fund.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UnitAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unitaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
