// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/vehicle"
	"github.com/google/uuid"
)

// VehicleCreate is the builder for creating a Vehicle entity.
type VehicleCreate struct {
	config
	mutation *VehicleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *VehicleCreate) SetTenantID(v uuid.UUID) *VehicleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VehicleCreate) SetCreatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableCreatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VehicleCreate) SetUpdatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableUpdatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *VehicleCreate) SetMetadata(v map[string]interface{}) *VehicleCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUnitID sets the "unit_id" field.
func (_c *VehicleCreate) SetUnitID(v uuid.UUID) *VehicleCreate {
	_c.mutation.SetUnitID(v)
	return _c
}

// SetPartyID sets the "party_id" field.
func (_c *VehicleCreate) SetPartyID(v uuid.UUID) *VehicleCreate {
	_c.mutation.SetPartyID(v)
	return _c
}

// SetNillablePartyID sets the "party_id" field if the given value is not nil.
func (_c *VehicleCreate) SetNillablePartyID(v *uuid.UUID) *VehicleCreate {
	if v != nil {
		_c.SetPartyID(*v)
	}
	return _c
}

// SetPlate sets the "plate" field.
func (_c *VehicleCreate) SetPlate(v string) *VehicleCreate {
	_c.mutation.SetPlate(v)
	return _c
}

// SetMake sets the "make" field.
func (_c *VehicleCreate) SetMake(v string) *VehicleCreate {
	_c.mutation.SetMake(v)
	return _c
}

// SetNillableMake sets the "make" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableMake(v *string) *VehicleCreate {
	if v != nil {
		_c.SetMake(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *VehicleCreate) SetModel(v string) *VehicleCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableModel(v *string) *VehicleCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetColour sets the "colour" field.
func (_c *VehicleCreate) SetColour(v string) *VehicleCreate {
	_c.mutation.SetColour(v)
	return _c
}

// SetNillableColour sets the "colour" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableColour(v *string) *VehicleCreate {
	if v != nil {
		_c.SetColour(*v)
	}
	return _c
}

// SetStickerNumber sets the "sticker_number" field.
func (_c *VehicleCreate) SetStickerNumber(v string) *VehicleCreate {
	_c.mutation.SetStickerNumber(v)
	return _c
}

// SetNillableStickerNumber sets the "sticker_number" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableStickerNumber(v *string) *VehicleCreate {
	if v != nil {
		_c.SetStickerNumber(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VehicleCreate) SetStatus(v vehicle.Status) *VehicleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableStatus(v *vehicle.Status) *VehicleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemovedAt sets the "removed_at" field.
func (_c *VehicleCreate) SetRemovedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetRemovedAt(v)
	return _c
}

// SetNillableRemovedAt sets the "removed_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableRemovedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetRemovedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VehicleCreate) SetID(v uuid.UUID) *VehicleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableID(v *uuid.UUID) *VehicleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the VehicleMutation object of the builder.
func (_c *VehicleCreate) Mutation() *VehicleMutation {
	return _c.mutation
}

// Save creates the Vehicle in the database.
func (_c *VehicleCreate) Save(ctx context.Context) (*Vehicle, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VehicleCreate) SaveX(ctx context.Context) *Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VehicleCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if vehicle.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized vehicle.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := vehicle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if vehicle.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized vehicle.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := vehicle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := vehicle.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if vehicle.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized vehicle.DefaultID (forgotten import ent/runtime?)")
		}
		v := vehicle.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *VehicleCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Vehicle.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vehicle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vehicle.updated_at"`)}
	}
	if _, ok := _c.mutation.UnitID(); !ok {
		return &ValidationError{Name: "unit_id", err: errors.New(`ent: missing required field "Vehicle.unit_id"`)}
	}
	if _, ok := _c.mutation.Plate(); !ok {
		return &ValidationError{Name: "plate", err: errors.New(`ent: missing required field "Vehicle.plate"`)}
	}
	if v, ok := _c.mutation.Plate(); ok {
		if err := vehicle.PlateValidator(v); err != nil {
			return &ValidationError{Name: "plate", err: fmt.Errorf(`ent: validator failed for field "Vehicle.plate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Vehicle.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := vehicle.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Vehicle.status": %w`, err)}
		}
	}
	return nil
}

func (_c *VehicleCreate) sqlSave(ctx context.Context) (*Vehicle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VehicleCreate) createSpec() (*Vehicle, *sqlgraph.CreateSpec) {
	var (
		_node = &Vehicle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vehicle.Table, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(vehicle.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vehicle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(vehicle.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.UnitID(); ok {
		_spec.SetField(vehicle.FieldUnitID, field.TypeUUID, value)
		_node.UnitID = value
	}
	if value, ok := _c.mutation.PartyID(); ok {
		_spec.SetField(vehicle.FieldPartyID, field.TypeUUID, value)
		_node.PartyID = &value
	}
	if value, ok := _c.mutation.Plate(); ok {
		_spec.SetField(vehicle.FieldPlate, field.TypeString, value)
		_node.Plate = value
	}
	if value, ok := _c.mutation.Make(); ok {
		_spec.SetField(vehicle.FieldMake, field.TypeString, value)
		_node.Make = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(vehicle.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Colour(); ok {
		_spec.SetField(vehicle.FieldColour, field.TypeString, value)
		_node.Colour = value
	}
	if value, ok := _c.mutation.StickerNumber(); ok {
		_spec.SetField(vehicle.FieldStickerNumber, field.TypeString, value)
		_node.StickerNumber = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(vehicle.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RemovedAt(); ok {
		_spec.SetField(vehicle.FieldRemovedAt, field.TypeTime, value)
		_node.RemovedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Vehicle.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VehicleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *VehicleCreate) OnConflict(opts ...sql.ConflictOption) *VehicleUpsertOne {
	_c.conflict = opts
	return &VehicleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Vehicle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VehicleCreate) OnConflictColumns(columns ...string) *VehicleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VehicleUpsertOne{
		create: _c,
	}
}

type (
	// VehicleUpsertOne is the builder for "upsert"-ing
	//  one Vehicle node.
	VehicleUpsertOne struct {
		create *VehicleCreate
	}

	// VehicleUpsert is the "OnConflict" setter.
	VehicleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VehicleUpsert) SetUpdatedAt(v time.Time) *VehicleUpsert {
	u.Set(vehicle.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateUpdatedAt() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldUpdatedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *VehicleUpsert) SetMetadata(v map[string]interface{}) *VehicleUpsert {
	u.Set(vehicle.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateMetadata() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *VehicleUpsert) ClearMetadata() *VehicleUpsert {
	u.SetNull(vehicle.FieldMetadata)
	return u
}

// SetUnitID sets the "unit_id" field.
func (u *VehicleUpsert) SetUnitID(v uuid.UUID) *VehicleUpsert {
	u.Set(vehicle.FieldUnitID, v)
	return u
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateUnitID() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldUnitID)
	return u
}

// SetPartyID sets the "party_id" field.
func (u *VehicleUpsert) SetPartyID(v uuid.UUID) *VehicleUpsert {
	u.Set(vehicle.FieldPartyID, v)
	return u
}

// UpdatePartyID sets the "party_id" field to the value that was provided on create.
func (u *VehicleUpsert) UpdatePartyID() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldPartyID)
	return u
}

// ClearPartyID clears the value of the "party_id" field.
func (u *VehicleUpsert) ClearPartyID() *VehicleUpsert {
	u.SetNull(vehicle.FieldPartyID)
	return u
}

// SetPlate sets the "plate" field.
func (u *VehicleUpsert) SetPlate(v string) *VehicleUpsert {
	u.Set(vehicle.FieldPlate, v)
	return u
}

// UpdatePlate sets the "plate" field to the value that was provided on create.
func (u *VehicleUpsert) UpdatePlate() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldPlate)
	return u
}

// SetMake sets the "make" field.
func (u *VehicleUpsert) SetMake(v string) *VehicleUpsert {
	u.Set(vehicle.FieldMake, v)
	return u
}

// UpdateMake sets the "make" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateMake() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldMake)
	return u
}

// ClearMake clears the value of the "make" field.
func (u *VehicleUpsert) ClearMake() *VehicleUpsert {
	u.SetNull(vehicle.FieldMake)
	return u
}

// SetModel sets the "model" field.
func (u *VehicleUpsert) SetModel(v string) *VehicleUpsert {
	u.Set(vehicle.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateModel() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *VehicleUpsert) ClearModel() *VehicleUpsert {
	u.SetNull(vehicle.FieldModel)
	return u
}

// SetColour sets the "colour" field.
func (u *VehicleUpsert) SetColour(v string) *VehicleUpsert {
	u.Set(vehicle.FieldColour, v)
	return u
}

// UpdateColour sets the "colour" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateColour() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldColour)
	return u
}

// ClearColour clears the value of the "colour" field.
func (u *VehicleUpsert) ClearColour() *VehicleUpsert {
	u.SetNull(vehicle.FieldColour)
	return u
}

// SetStickerNumber sets the "sticker_number" field.
func (u *VehicleUpsert) SetStickerNumber(v string) *VehicleUpsert {
	u.Set(vehicle.FieldStickerNumber, v)
	return u
}

// UpdateStickerNumber sets the "sticker_number" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateStickerNumber() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldStickerNumber)
	return u
}

// ClearStickerNumber clears the value of the "sticker_number" field.
func (u *VehicleUpsert) ClearStickerNumber() *VehicleUpsert {
	u.SetNull(vehicle.FieldStickerNumber)
	return u
}

// SetStatus sets the "status" field.
func (u *VehicleUpsert) SetStatus(v vehicle.Status) *VehicleUpsert {
	u.Set(vehicle.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateStatus() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldStatus)
	return u
}

// SetRemovedAt sets the "removed_at" field.
func (u *VehicleUpsert) SetRemovedAt(v time.Time) *VehicleUpsert {
	u.Set(vehicle.FieldRemovedAt, v)
	return u
}

// UpdateRemovedAt sets the "removed_at" field to the value that was provided on create.
func (u *VehicleUpsert) UpdateRemovedAt() *VehicleUpsert {
	u.SetExcluded(vehicle.FieldRemovedAt)
	return u
}

// ClearRemovedAt clears the value of the "removed_at" field.
func (u *VehicleUpsert) ClearRemovedAt() *VehicleUpsert {
	u.SetNull(vehicle.FieldRemovedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Vehicle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(vehicle.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VehicleUpsertOne) UpdateNewValues() *VehicleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(vehicle.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(vehicle.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(vehicle.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Vehicle.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VehicleUpsertOne) Ignore() *VehicleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VehicleUpsertOne) DoNothing() *VehicleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VehicleCreate.OnConflict
// documentation for more info.
func (u *VehicleUpsertOne) Update(set func(*VehicleUpsert)) *VehicleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VehicleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VehicleUpsertOne) SetUpdatedAt(v time.Time) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateUpdatedAt() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *VehicleUpsertOne) SetMetadata(v map[string]interface{}) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateMetadata() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *VehicleUpsertOne) ClearMetadata() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearMetadata()
	})
}

// SetUnitID sets the "unit_id" field.
func (u *VehicleUpsertOne) SetUnitID(v uuid.UUID) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetUnitID(v)
	})
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateUnitID() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateUnitID()
	})
}

// SetPartyID sets the "party_id" field.
func (u *VehicleUpsertOne) SetPartyID(v uuid.UUID) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetPartyID(v)
	})
}

// UpdatePartyID sets the "party_id" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdatePartyID() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdatePartyID()
	})
}

// ClearPartyID clears the value of the "party_id" field.
func (u *VehicleUpsertOne) ClearPartyID() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearPartyID()
	})
}

// SetPlate sets the "plate" field.
func (u *VehicleUpsertOne) SetPlate(v string) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetPlate(v)
	})
}

// UpdatePlate sets the "plate" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdatePlate() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdatePlate()
	})
}

// SetMake sets the "make" field.
func (u *VehicleUpsertOne) SetMake(v string) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetMake(v)
	})
}

// UpdateMake sets the "make" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateMake() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateMake()
	})
}

// ClearMake clears the value of the "make" field.
func (u *VehicleUpsertOne) ClearMake() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearMake()
	})
}

// SetModel sets the "model" field.
func (u *VehicleUpsertOne) SetModel(v string) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateModel() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *VehicleUpsertOne) ClearModel() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearModel()
	})
}

// SetColour sets the "colour" field.
func (u *VehicleUpsertOne) SetColour(v string) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetColour(v)
	})
}

// UpdateColour sets the "colour" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateColour() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateColour()
	})
}

// ClearColour clears the value of the "colour" field.
func (u *VehicleUpsertOne) ClearColour() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearColour()
	})
}

// SetStickerNumber sets the "sticker_number" field.
func (u *VehicleUpsertOne) SetStickerNumber(v string) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetStickerNumber(v)
	})
}

// UpdateStickerNumber sets the "sticker_number" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateStickerNumber() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateStickerNumber()
	})
}

// ClearStickerNumber clears the value of the "sticker_number" field.
func (u *VehicleUpsertOne) ClearStickerNumber() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearStickerNumber()
	})
}

// SetStatus sets the "status" field.
func (u *VehicleUpsertOne) SetStatus(v vehicle.Status) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateStatus() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateStatus()
	})
}

// SetRemovedAt sets the "removed_at" field.
func (u *VehicleUpsertOne) SetRemovedAt(v time.Time) *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.SetRemovedAt(v)
	})
}

// UpdateRemovedAt sets the "removed_at" field to the value that was provided on create.
func (u *VehicleUpsertOne) UpdateRemovedAt() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateRemovedAt()
	})
}

// ClearRemovedAt clears the value of the "removed_at" field.
func (u *VehicleUpsertOne) ClearRemovedAt() *VehicleUpsertOne {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearRemovedAt()
	})
}

// Exec executes the query.
func (u *VehicleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VehicleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VehicleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VehicleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: VehicleUpsertOne.ID is not supported by MySQL driver. Use VehicleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VehicleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VehicleCreateBulk is the builder for creating many Vehicle entities in bulk.
type VehicleCreateBulk struct {
	config
	err      error
	builders []*VehicleCreate
	conflict []sql.ConflictOption
}

// Save creates the Vehicle entities in the database.
func (_c *VehicleCreateBulk) Save(ctx context.Context) ([]*Vehicle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vehicle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VehicleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VehicleCreateBulk) SaveX(ctx context.Context) []*Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Vehicle.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VehicleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *VehicleCreateBulk) OnConflict(opts ...sql.ConflictOption) *VehicleUpsertBulk {
	_c.conflict = opts
	return &VehicleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Vehicle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VehicleCreateBulk) OnConflictColumns(columns ...string) *VehicleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VehicleUpsertBulk{
		create: _c,
	}
}

// VehicleUpsertBulk is the builder for "upsert"-ing
// a bulk of Vehicle nodes.
type VehicleUpsertBulk struct {
	create *VehicleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Vehicle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(vehicle.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VehicleUpsertBulk) UpdateNewValues() *VehicleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(vehicle.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(vehicle.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(vehicle.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Vehicle.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VehicleUpsertBulk) Ignore() *VehicleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VehicleUpsertBulk) DoNothing() *VehicleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VehicleCreateBulk.OnConflict
// documentation for more info.
func (u *VehicleUpsertBulk) Update(set func(*VehicleUpsert)) *VehicleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VehicleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VehicleUpsertBulk) SetUpdatedAt(v time.Time) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateUpdatedAt() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *VehicleUpsertBulk) SetMetadata(v map[string]interface{}) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateMetadata() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *VehicleUpsertBulk) ClearMetadata() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearMetadata()
	})
}

// SetUnitID sets the "unit_id" field.
func (u *VehicleUpsertBulk) SetUnitID(v uuid.UUID) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetUnitID(v)
	})
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateUnitID() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateUnitID()
	})
}

// SetPartyID sets the "party_id" field.
func (u *VehicleUpsertBulk) SetPartyID(v uuid.UUID) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetPartyID(v)
	})
}

// UpdatePartyID sets the "party_id" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdatePartyID() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdatePartyID()
	})
}

// ClearPartyID clears the value of the "party_id" field.
func (u *VehicleUpsertBulk) ClearPartyID() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearPartyID()
	})
}

// SetPlate sets the "plate" field.
func (u *VehicleUpsertBulk) SetPlate(v string) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetPlate(v)
	})
}

// UpdatePlate sets the "plate" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdatePlate() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdatePlate()
	})
}

// SetMake sets the "make" field.
func (u *VehicleUpsertBulk) SetMake(v string) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetMake(v)
	})
}

// UpdateMake sets the "make" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateMake() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateMake()
	})
}

// ClearMake clears the value of the "make" field.
func (u *VehicleUpsertBulk) ClearMake() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearMake()
	})
}

// SetModel sets the "model" field.
func (u *VehicleUpsertBulk) SetModel(v string) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateModel() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *VehicleUpsertBulk) ClearModel() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearModel()
	})
}

// SetColour sets the "colour" field.
func (u *VehicleUpsertBulk) SetColour(v string) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetColour(v)
	})
}

// UpdateColour sets the "colour" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateColour() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateColour()
	})
}

// ClearColour clears the value of the "colour" field.
func (u *VehicleUpsertBulk) ClearColour() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearColour()
	})
}

// SetStickerNumber sets the "sticker_number" field.
func (u *VehicleUpsertBulk) SetStickerNumber(v string) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetStickerNumber(v)
	})
}

// UpdateStickerNumber sets the "sticker_number" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateStickerNumber() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateStickerNumber()
	})
}

// ClearStickerNumber clears the value of the "sticker_number" field.
func (u *VehicleUpsertBulk) ClearStickerNumber() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearStickerNumber()
	})
}

// SetStatus sets the "status" field.
func (u *VehicleUpsertBulk) SetStatus(v vehicle.Status) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateStatus() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateStatus()
	})
}

// SetRemovedAt sets the "removed_at" field.
func (u *VehicleUpsertBulk) SetRemovedAt(v time.Time) *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.SetRemovedAt(v)
	})
}

// UpdateRemovedAt sets the "removed_at" field to the value that was provided on create.
func (u *VehicleUpsertBulk) UpdateRemovedAt() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.UpdateRemovedAt()
	})
}

// ClearRemovedAt clears the value of the "removed_at" field.
func (u *VehicleUpsertBulk) ClearRemovedAt() *VehicleUpsertBulk {
	return u.Update(func(s *VehicleUpsert) {
		s.ClearRemovedAt()
	})
}

// Exec executes the query.
func (u *VehicleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VehicleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VehicleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VehicleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
