// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/maskani-api/internal/ent/vendor"
	"github.com/bengobox/maskani-api/internal/ent/vendordocument"
	"github.com/google/uuid"
)

// VendorDocumentCreate is the builder for creating a VendorDocument entity.
type VendorDocumentCreate struct {
	config
	mutation *VendorDocumentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *VendorDocumentCreate) SetTenantID(v uuid.UUID) *VendorDocumentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VendorDocumentCreate) SetCreatedAt(v time.Time) *VendorDocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableCreatedAt(v *time.Time) *VendorDocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VendorDocumentCreate) SetUpdatedAt(v time.Time) *VendorDocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableUpdatedAt(v *time.Time) *VendorDocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *VendorDocumentCreate) SetMetadata(v map[string]interface{}) *VendorDocumentCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetVendorID sets the "vendor_id" field.
func (_c *VendorDocumentCreate) SetVendorID(v uuid.UUID) *VendorDocumentCreate {
	_c.mutation.SetVendorID(v)
	return _c
}

// SetDocType sets the "doc_type" field.
func (_c *VendorDocumentCreate) SetDocType(v string) *VendorDocumentCreate {
	_c.mutation.SetDocType(v)
	return _c
}

// SetNumber sets the "number" field.
func (_c *VendorDocumentCreate) SetNumber(v string) *VendorDocumentCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableNumber(v *string) *VendorDocumentCreate {
	if v != nil {
		_c.SetNumber(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *VendorDocumentCreate) SetIssuedAt(v time.Time) *VendorDocumentCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableIssuedAt(v *time.Time) *VendorDocumentCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *VendorDocumentCreate) SetExpiresAt(v time.Time) *VendorDocumentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableExpiresAt(v *time.Time) *VendorDocumentCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetFileKey sets the "file_key" field.
func (_c *VendorDocumentCreate) SetFileKey(v string) *VendorDocumentCreate {
	_c.mutation.SetFileKey(v)
	return _c
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableFileKey(v *string) *VendorDocumentCreate {
	if v != nil {
		_c.SetFileKey(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VendorDocumentCreate) SetStatus(v vendordocument.Status) *VendorDocumentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableStatus(v *vendordocument.Status) *VendorDocumentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVerifiedBy sets the "verified_by" field.
func (_c *VendorDocumentCreate) SetVerifiedBy(v uuid.UUID) *VendorDocumentCreate {
	_c.mutation.SetVerifiedBy(v)
	return _c
}

// SetNillableVerifiedBy sets the "verified_by" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableVerifiedBy(v *uuid.UUID) *VendorDocumentCreate {
	if v != nil {
		_c.SetVerifiedBy(*v)
	}
	return _c
}

// SetLastAlertDays sets the "last_alert_days" field.
func (_c *VendorDocumentCreate) SetLastAlertDays(v int) *VendorDocumentCreate {
	_c.mutation.SetLastAlertDays(v)
	return _c
}

// SetNillableLastAlertDays sets the "last_alert_days" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableLastAlertDays(v *int) *VendorDocumentCreate {
	if v != nil {
		_c.SetLastAlertDays(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VendorDocumentCreate) SetID(v uuid.UUID) *VendorDocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VendorDocumentCreate) SetNillableID(v *uuid.UUID) *VendorDocumentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVendor sets the "vendor" edge to the Vendor entity.
func (_c *VendorDocumentCreate) SetVendor(v *Vendor) *VendorDocumentCreate {
	return _c.SetVendorID(v.ID)
}

// Mutation returns the VendorDocumentMutation object of the builder.
func (_c *VendorDocumentCreate) Mutation() *VendorDocumentMutation {
	return _c.mutation
}

// Save creates the VendorDocument in the database.
func (_c *VendorDocumentCreate) Save(ctx context.Context) (*VendorDocument, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VendorDocumentCreate) SaveX(ctx context.Context) *VendorDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VendorDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VendorDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VendorDocumentCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if vendordocument.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized vendordocument.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := vendordocument.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if vendordocument.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized vendordocument.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := vendordocument.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := vendordocument.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if vendordocument.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized vendordocument.DefaultID (forgotten import ent/runtime?)")
		}
		v := vendordocument.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *VendorDocumentCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "VendorDocument.tenant_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VendorDocument.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VendorDocument.updated_at"`)}
	}
	if _, ok := _c.mutation.VendorID(); !ok {
		return &ValidationError{Name: "vendor_id", err: errors.New(`ent: missing required field "VendorDocument.vendor_id"`)}
	}
	if _, ok := _c.mutation.DocType(); !ok {
		return &ValidationError{Name: "doc_type", err: errors.New(`ent: missing required field "VendorDocument.doc_type"`)}
	}
	if v, ok := _c.mutation.DocType(); ok {
		if err := vendordocument.DocTypeValidator(v); err != nil {
			return &ValidationError{Name: "doc_type", err: fmt.Errorf(`ent: validator failed for field "VendorDocument.doc_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VendorDocument.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := vendordocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VendorDocument.status": %w`, err)}
		}
	}
	if len(_c.mutation.VendorIDs()) == 0 {
		return &ValidationError{Name: "vendor", err: errors.New(`ent: missing required edge "VendorDocument.vendor"`)}
	}
	return nil
}

func (_c *VendorDocumentCreate) sqlSave(ctx context.Context) (*VendorDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VendorDocumentCreate) createSpec() (*VendorDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &VendorDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vendordocument.Table, sqlgraph.NewFieldSpec(vendordocument.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(vendordocument.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vendordocument.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vendordocument.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(vendordocument.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.DocType(); ok {
		_spec.SetField(vendordocument.FieldDocType, field.TypeString, value)
		_node.DocType = value
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(vendordocument.FieldNumber, field.TypeString, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(vendordocument.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(vendordocument.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.FileKey(); ok {
		_spec.SetField(vendordocument.FieldFileKey, field.TypeString, value)
		_node.FileKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(vendordocument.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.VerifiedBy(); ok {
		_spec.SetField(vendordocument.FieldVerifiedBy, field.TypeUUID, value)
		_node.VerifiedBy = &value
	}
	if value, ok := _c.mutation.LastAlertDays(); ok {
		_spec.SetField(vendordocument.FieldLastAlertDays, field.TypeInt, value)
		_node.LastAlertDays = &value
	}
	if nodes := _c.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vendordocument.VendorTable,
			Columns: []string{vendordocument.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VendorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VendorDocument.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VendorDocumentUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *VendorDocumentCreate) OnConflict(opts ...sql.ConflictOption) *VendorDocumentUpsertOne {
	_c.conflict = opts
	return &VendorDocumentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VendorDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VendorDocumentCreate) OnConflictColumns(columns ...string) *VendorDocumentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VendorDocumentUpsertOne{
		create: _c,
	}
}

type (
	// VendorDocumentUpsertOne is the builder for "upsert"-ing
	//  one VendorDocument node.
	VendorDocumentUpsertOne struct {
		create *VendorDocumentCreate
	}

	// VendorDocumentUpsert is the "OnConflict" setter.
	VendorDocumentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VendorDocumentUpsert) SetUpdatedAt(v time.Time) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateUpdatedAt() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldUpdatedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *VendorDocumentUpsert) SetMetadata(v map[string]interface{}) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateMetadata() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *VendorDocumentUpsert) ClearMetadata() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldMetadata)
	return u
}

// SetVendorID sets the "vendor_id" field.
func (u *VendorDocumentUpsert) SetVendorID(v uuid.UUID) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldVendorID, v)
	return u
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateVendorID() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldVendorID)
	return u
}

// SetDocType sets the "doc_type" field.
func (u *VendorDocumentUpsert) SetDocType(v string) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldDocType, v)
	return u
}

// UpdateDocType sets the "doc_type" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateDocType() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldDocType)
	return u
}

// SetNumber sets the "number" field.
func (u *VendorDocumentUpsert) SetNumber(v string) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldNumber, v)
	return u
}

// UpdateNumber sets the "number" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateNumber() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldNumber)
	return u
}

// ClearNumber clears the value of the "number" field.
func (u *VendorDocumentUpsert) ClearNumber() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldNumber)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *VendorDocumentUpsert) SetIssuedAt(v time.Time) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateIssuedAt() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *VendorDocumentUpsert) ClearIssuedAt() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldIssuedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *VendorDocumentUpsert) SetExpiresAt(v time.Time) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateExpiresAt() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *VendorDocumentUpsert) ClearExpiresAt() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldExpiresAt)
	return u
}

// SetFileKey sets the "file_key" field.
func (u *VendorDocumentUpsert) SetFileKey(v string) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldFileKey, v)
	return u
}

// UpdateFileKey sets the "file_key" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateFileKey() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldFileKey)
	return u
}

// ClearFileKey clears the value of the "file_key" field.
func (u *VendorDocumentUpsert) ClearFileKey() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldFileKey)
	return u
}

// SetStatus sets the "status" field.
func (u *VendorDocumentUpsert) SetStatus(v vendordocument.Status) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateStatus() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldStatus)
	return u
}

// SetVerifiedBy sets the "verified_by" field.
func (u *VendorDocumentUpsert) SetVerifiedBy(v uuid.UUID) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldVerifiedBy, v)
	return u
}

// UpdateVerifiedBy sets the "verified_by" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateVerifiedBy() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldVerifiedBy)
	return u
}

// ClearVerifiedBy clears the value of the "verified_by" field.
func (u *VendorDocumentUpsert) ClearVerifiedBy() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldVerifiedBy)
	return u
}

// SetLastAlertDays sets the "last_alert_days" field.
func (u *VendorDocumentUpsert) SetLastAlertDays(v int) *VendorDocumentUpsert {
	u.Set(vendordocument.FieldLastAlertDays, v)
	return u
}

// UpdateLastAlertDays sets the "last_alert_days" field to the value that was provided on create.
func (u *VendorDocumentUpsert) UpdateLastAlertDays() *VendorDocumentUpsert {
	u.SetExcluded(vendordocument.FieldLastAlertDays)
	return u
}

// AddLastAlertDays adds v to the "last_alert_days" field.
func (u *VendorDocumentUpsert) AddLastAlertDays(v int) *VendorDocumentUpsert {
	u.Add(vendordocument.FieldLastAlertDays, v)
	return u
}

// ClearLastAlertDays clears the value of the "last_alert_days" field.
func (u *VendorDocumentUpsert) ClearLastAlertDays() *VendorDocumentUpsert {
	u.SetNull(vendordocument.FieldLastAlertDays)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.VendorDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(vendordocument.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VendorDocumentUpsertOne) UpdateNewValues() *VendorDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(vendordocument.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(vendordocument.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(vendordocument.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VendorDocument.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VendorDocumentUpsertOne) Ignore() *VendorDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VendorDocumentUpsertOne) DoNothing() *VendorDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VendorDocumentCreate.OnConflict
// documentation for more info.
func (u *VendorDocumentUpsertOne) Update(set func(*VendorDocumentUpsert)) *VendorDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VendorDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VendorDocumentUpsertOne) SetUpdatedAt(v time.Time) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateUpdatedAt() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *VendorDocumentUpsertOne) SetMetadata(v map[string]interface{}) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateMetadata() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *VendorDocumentUpsertOne) ClearMetadata() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearMetadata()
	})
}

// SetVendorID sets the "vendor_id" field.
func (u *VendorDocumentUpsertOne) SetVendorID(v uuid.UUID) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetVendorID(v)
	})
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateVendorID() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateVendorID()
	})
}

// SetDocType sets the "doc_type" field.
func (u *VendorDocumentUpsertOne) SetDocType(v string) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetDocType(v)
	})
}

// UpdateDocType sets the "doc_type" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateDocType() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateDocType()
	})
}

// SetNumber sets the "number" field.
func (u *VendorDocumentUpsertOne) SetNumber(v string) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetNumber(v)
	})
}

// UpdateNumber sets the "number" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateNumber() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateNumber()
	})
}

// ClearNumber clears the value of the "number" field.
func (u *VendorDocumentUpsertOne) ClearNumber() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearNumber()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *VendorDocumentUpsertOne) SetIssuedAt(v time.Time) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateIssuedAt() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *VendorDocumentUpsertOne) ClearIssuedAt() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearIssuedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *VendorDocumentUpsertOne) SetExpiresAt(v time.Time) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateExpiresAt() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *VendorDocumentUpsertOne) ClearExpiresAt() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearExpiresAt()
	})
}

// SetFileKey sets the "file_key" field.
func (u *VendorDocumentUpsertOne) SetFileKey(v string) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetFileKey(v)
	})
}

// UpdateFileKey sets the "file_key" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateFileKey() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateFileKey()
	})
}

// ClearFileKey clears the value of the "file_key" field.
func (u *VendorDocumentUpsertOne) ClearFileKey() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearFileKey()
	})
}

// SetStatus sets the "status" field.
func (u *VendorDocumentUpsertOne) SetStatus(v vendordocument.Status) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateStatus() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateStatus()
	})
}

// SetVerifiedBy sets the "verified_by" field.
func (u *VendorDocumentUpsertOne) SetVerifiedBy(v uuid.UUID) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetVerifiedBy(v)
	})
}

// UpdateVerifiedBy sets the "verified_by" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateVerifiedBy() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateVerifiedBy()
	})
}

// ClearVerifiedBy clears the value of the "verified_by" field.
func (u *VendorDocumentUpsertOne) ClearVerifiedBy() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearVerifiedBy()
	})
}

// SetLastAlertDays sets the "last_alert_days" field.
func (u *VendorDocumentUpsertOne) SetLastAlertDays(v int) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetLastAlertDays(v)
	})
}

// AddLastAlertDays adds v to the "last_alert_days" field.
func (u *VendorDocumentUpsertOne) AddLastAlertDays(v int) *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.AddLastAlertDays(v)
	})
}

// UpdateLastAlertDays sets the "last_alert_days" field to the value that was provided on create.
func (u *VendorDocumentUpsertOne) UpdateLastAlertDays() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateLastAlertDays()
	})
}

// ClearLastAlertDays clears the value of the "last_alert_days" field.
func (u *VendorDocumentUpsertOne) ClearLastAlertDays() *VendorDocumentUpsertOne {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearLastAlertDays()
	})
}

// Exec executes the query.
func (u *VendorDocumentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VendorDocumentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VendorDocumentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VendorDocumentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: VendorDocumentUpsertOne.ID is not supported by MySQL driver. Use VendorDocumentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VendorDocumentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VendorDocumentCreateBulk is the builder for creating many VendorDocument entities in bulk.
type VendorDocumentCreateBulk struct {
	config
	err      error
	builders []*VendorDocumentCreate
	conflict []sql.ConflictOption
}

// Save creates the VendorDocument entities in the database.
func (_c *VendorDocumentCreateBulk) Save(ctx context.Context) ([]*VendorDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VendorDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VendorDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VendorDocumentCreateBulk) SaveX(ctx context.Context) []*VendorDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VendorDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VendorDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VendorDocument.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VendorDocumentUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *VendorDocumentCreateBulk) OnConflict(opts ...sql.ConflictOption) *VendorDocumentUpsertBulk {
	_c.conflict = opts
	return &VendorDocumentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VendorDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VendorDocumentCreateBulk) OnConflictColumns(columns ...string) *VendorDocumentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VendorDocumentUpsertBulk{
		create: _c,
	}
}

// VendorDocumentUpsertBulk is the builder for "upsert"-ing
// a bulk of VendorDocument nodes.
type VendorDocumentUpsertBulk struct {
	create *VendorDocumentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VendorDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(vendordocument.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VendorDocumentUpsertBulk) UpdateNewValues() *VendorDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(vendordocument.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(vendordocument.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(vendordocument.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VendorDocument.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VendorDocumentUpsertBulk) Ignore() *VendorDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VendorDocumentUpsertBulk) DoNothing() *VendorDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VendorDocumentCreateBulk.OnConflict
// documentation for more info.
func (u *VendorDocumentUpsertBulk) Update(set func(*VendorDocumentUpsert)) *VendorDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VendorDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VendorDocumentUpsertBulk) SetUpdatedAt(v time.Time) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateUpdatedAt() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *VendorDocumentUpsertBulk) SetMetadata(v map[string]interface{}) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateMetadata() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *VendorDocumentUpsertBulk) ClearMetadata() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearMetadata()
	})
}

// SetVendorID sets the "vendor_id" field.
func (u *VendorDocumentUpsertBulk) SetVendorID(v uuid.UUID) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetVendorID(v)
	})
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateVendorID() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateVendorID()
	})
}

// SetDocType sets the "doc_type" field.
func (u *VendorDocumentUpsertBulk) SetDocType(v string) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetDocType(v)
	})
}

// UpdateDocType sets the "doc_type" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateDocType() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateDocType()
	})
}

// SetNumber sets the "number" field.
func (u *VendorDocumentUpsertBulk) SetNumber(v string) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetNumber(v)
	})
}

// UpdateNumber sets the "number" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateNumber() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateNumber()
	})
}

// ClearNumber clears the value of the "number" field.
func (u *VendorDocumentUpsertBulk) ClearNumber() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearNumber()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *VendorDocumentUpsertBulk) SetIssuedAt(v time.Time) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateIssuedAt() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *VendorDocumentUpsertBulk) ClearIssuedAt() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearIssuedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *VendorDocumentUpsertBulk) SetExpiresAt(v time.Time) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateExpiresAt() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *VendorDocumentUpsertBulk) ClearExpiresAt() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearExpiresAt()
	})
}

// SetFileKey sets the "file_key" field.
func (u *VendorDocumentUpsertBulk) SetFileKey(v string) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetFileKey(v)
	})
}

// UpdateFileKey sets the "file_key" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateFileKey() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateFileKey()
	})
}

// ClearFileKey clears the value of the "file_key" field.
func (u *VendorDocumentUpsertBulk) ClearFileKey() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearFileKey()
	})
}

// SetStatus sets the "status" field.
func (u *VendorDocumentUpsertBulk) SetStatus(v vendordocument.Status) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateStatus() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateStatus()
	})
}

// SetVerifiedBy sets the "verified_by" field.
func (u *VendorDocumentUpsertBulk) SetVerifiedBy(v uuid.UUID) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetVerifiedBy(v)
	})
}

// UpdateVerifiedBy sets the "verified_by" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateVerifiedBy() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateVerifiedBy()
	})
}

// ClearVerifiedBy clears the value of the "verified_by" field.
func (u *VendorDocumentUpsertBulk) ClearVerifiedBy() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearVerifiedBy()
	})
}

// SetLastAlertDays sets the "last_alert_days" field.
func (u *VendorDocumentUpsertBulk) SetLastAlertDays(v int) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.SetLastAlertDays(v)
	})
}

// AddLastAlertDays adds v to the "last_alert_days" field.
func (u *VendorDocumentUpsertBulk) AddLastAlertDays(v int) *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.AddLastAlertDays(v)
	})
}

// UpdateLastAlertDays sets the "last_alert_days" field to the value that was provided on create.
func (u *VendorDocumentUpsertBulk) UpdateLastAlertDays() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.UpdateLastAlertDays()
	})
}

// ClearLastAlertDays clears the value of the "last_alert_days" field.
func (u *VendorDocumentUpsertBulk) ClearLastAlertDays() *VendorDocumentUpsertBulk {
	return u.Update(func(s *VendorDocumentUpsert) {
		s.ClearLastAlertDays()
	})
}

// Exec executes the query.
func (u *VendorDocumentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VendorDocumentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VendorDocumentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VendorDocumentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
