// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/maskani-api/internal/ent/visitorpass"
	"github.com/google/uuid"
)

// VisitorPass is the model entity for the VisitorPass schema.
type VisitorPass struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// PropertyID holds the value of the "property_id" field.
	PropertyID uuid.UUID `json:"property_id,omitempty"`
	// UnitID holds the value of the "unit_id" field.
	UnitID *uuid.UUID `json:"unit_id,omitempty"`
	// HostPartyID holds the value of the "host_party_id" field.
	HostPartyID *uuid.UUID `json:"host_party_id,omitempty"`
	// CreatedByKind holds the value of the "created_by_kind" field.
	CreatedByKind visitorpass.CreatedByKind `json:"created_by_kind,omitempty"`
	// CreatedByID holds the value of the "created_by_id" field.
	CreatedByID *uuid.UUID `json:"created_by_id,omitempty"`
	// PassType holds the value of the "pass_type" field.
	PassType visitorpass.PassType `json:"pass_type,omitempty"`
	// VisitorName holds the value of the "visitor_name" field.
	VisitorName string `json:"visitor_name,omitempty"`
	// VisitorPhone holds the value of the "visitor_phone" field.
	VisitorPhone string `json:"visitor_phone,omitempty"`
	// VehiclePlate holds the value of the "vehicle_plate" field.
	VehiclePlate string `json:"vehicle_plate,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash string `json:"-"`
	// last two digits, for staff lookups
	CodeHint string `json:"code_hint,omitempty"`
	// QrTokenHash holds the value of the "qr_token_hash" field.
	QrTokenHash string `json:"-"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidTo holds the value of the "valid_to" field.
	ValidTo time.Time `json:"valid_to,omitempty"`
	// {"days":[1,2,3],"from":"08:00","to":"17:00"}
	Recurrence map[string]interface{} `json:"recurrence,omitempty"`
	// MaxEntries holds the value of the "max_entries" field.
	MaxEntries int `json:"max_entries,omitempty"`
	// EntriesUsed holds the value of the "entries_used" field.
	EntriesUsed int `json:"entries_used,omitempty"`
	// WorkOrderID holds the value of the "work_order_id" field.
	WorkOrderID *uuid.UUID `json:"work_order_id,omitempty"`
	// Status holds the value of the "status" field.
	Status visitorpass.Status `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VisitorPass) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case visitorpass.FieldUnitID, visitorpass.FieldHostPartyID, visitorpass.FieldCreatedByID, visitorpass.FieldWorkOrderID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case visitorpass.FieldMetadata, visitorpass.FieldRecurrence:
			values[i] = new([]byte)
		case visitorpass.FieldMaxEntries, visitorpass.FieldEntriesUsed:
			values[i] = new(sql.NullInt64)
		case visitorpass.FieldCreatedByKind, visitorpass.FieldPassType, visitorpass.FieldVisitorName, visitorpass.FieldVisitorPhone, visitorpass.FieldVehiclePlate, visitorpass.FieldCodeHash, visitorpass.FieldCodeHint, visitorpass.FieldQrTokenHash, visitorpass.FieldStatus, visitorpass.FieldNotes:
			values[i] = new(sql.NullString)
		case visitorpass.FieldCreatedAt, visitorpass.FieldUpdatedAt, visitorpass.FieldValidFrom, visitorpass.FieldValidTo:
			values[i] = new(sql.NullTime)
		case visitorpass.FieldID, visitorpass.FieldTenantID, visitorpass.FieldPropertyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VisitorPass fields.
func (_m *VisitorPass) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case visitorpass.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case visitorpass.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case visitorpass.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case visitorpass.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case visitorpass.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case visitorpass.FieldPropertyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field property_id", values[i])
			} else if value != nil {
				_m.PropertyID = *value
			}
		case visitorpass.FieldUnitID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field unit_id", values[i])
			} else if value.Valid {
				_m.UnitID = new(uuid.UUID)
				*_m.UnitID = *value.S.(*uuid.UUID)
			}
		case visitorpass.FieldHostPartyID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field host_party_id", values[i])
			} else if value.Valid {
				_m.HostPartyID = new(uuid.UUID)
				*_m.HostPartyID = *value.S.(*uuid.UUID)
			}
		case visitorpass.FieldCreatedByKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_kind", values[i])
			} else if value.Valid {
				_m.CreatedByKind = visitorpass.CreatedByKind(value.String)
			}
		case visitorpass.FieldCreatedByID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value.Valid {
				_m.CreatedByID = new(uuid.UUID)
				*_m.CreatedByID = *value.S.(*uuid.UUID)
			}
		case visitorpass.FieldPassType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pass_type", values[i])
			} else if value.Valid {
				_m.PassType = visitorpass.PassType(value.String)
			}
		case visitorpass.FieldVisitorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visitor_name", values[i])
			} else if value.Valid {
				_m.VisitorName = value.String
			}
		case visitorpass.FieldVisitorPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visitor_phone", values[i])
			} else if value.Valid {
				_m.VisitorPhone = value.String
			}
		case visitorpass.FieldVehiclePlate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vehicle_plate", values[i])
			} else if value.Valid {
				_m.VehiclePlate = value.String
			}
		case visitorpass.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				_m.CodeHash = value.String
			}
		case visitorpass.FieldCodeHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hint", values[i])
			} else if value.Valid {
				_m.CodeHint = value.String
			}
		case visitorpass.FieldQrTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_token_hash", values[i])
			} else if value.Valid {
				_m.QrTokenHash = value.String
			}
		case visitorpass.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case visitorpass.FieldValidTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_to", values[i])
			} else if value.Valid {
				_m.ValidTo = value.Time
			}
		case visitorpass.FieldRecurrence:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recurrence", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Recurrence); err != nil {
					return fmt.Errorf("unmarshal field recurrence: %w", err)
				}
			}
		case visitorpass.FieldMaxEntries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_entries", values[i])
			} else if value.Valid {
				_m.MaxEntries = int(value.Int64)
			}
		case visitorpass.FieldEntriesUsed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entries_used", values[i])
			} else if value.Valid {
				_m.EntriesUsed = int(value.Int64)
			}
		case visitorpass.FieldWorkOrderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field work_order_id", values[i])
			} else if value.Valid {
				_m.WorkOrderID = new(uuid.UUID)
				*_m.WorkOrderID = *value.S.(*uuid.UUID)
			}
		case visitorpass.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = visitorpass.Status(value.String)
			}
		case visitorpass.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VisitorPass.
// This includes values selected through modifiers, order, etc.
func (_m *VisitorPass) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VisitorPass.
// Note that you need to call VisitorPass.Unwrap() before calling this method if this VisitorPass
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VisitorPass) Update() *VisitorPassUpdateOne {
	return NewVisitorPassClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VisitorPass entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VisitorPass) Unwrap() *VisitorPass {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VisitorPass is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VisitorPass) String() string {
	var builder strings.Builder
	builder.WriteString("VisitorPass(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("property_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertyID))
	builder.WriteString(", ")
	if v := _m.UnitID; v != nil {
		builder.WriteString("unit_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.HostPartyID; v != nil {
		builder.WriteString("host_party_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByKind))
	builder.WriteString(", ")
	if v := _m.CreatedByID; v != nil {
		builder.WriteString("created_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("pass_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PassType))
	builder.WriteString(", ")
	builder.WriteString("visitor_name=")
	builder.WriteString(_m.VisitorName)
	builder.WriteString(", ")
	builder.WriteString("visitor_phone=")
	builder.WriteString(_m.VisitorPhone)
	builder.WriteString(", ")
	builder.WriteString("vehicle_plate=")
	builder.WriteString(_m.VehiclePlate)
	builder.WriteString(", ")
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("code_hint=")
	builder.WriteString(_m.CodeHint)
	builder.WriteString(", ")
	builder.WriteString("qr_token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("valid_to=")
	builder.WriteString(_m.ValidTo.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("recurrence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Recurrence))
	builder.WriteString(", ")
	builder.WriteString("max_entries=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxEntries))
	builder.WriteString(", ")
	builder.WriteString("entries_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntriesUsed))
	builder.WriteString(", ")
	if v := _m.WorkOrderID; v != nil {
		builder.WriteString("work_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// VisitorPasses is a parsable slice of VisitorPass.
type VisitorPasses []*VisitorPass
