// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/maskani-api/internal/ent/visitor"
	"github.com/google/uuid"
)

// Visitor is the model entity for the Visitor schema.
type Visitor struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// PropertyID holds the value of the "property_id" field.
	PropertyID uuid.UUID `json:"property_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// normalised digits
	Phone string `json:"phone,omitempty"`
	// IDNumberHash holds the value of the "id_number_hash" field.
	IDNumberHash string `json:"-"`
	// last three characters
	IDNumberHint string `json:"id_number_hint,omitempty"`
	// the plate last seen, upper case without spaces
	VehiclePlate string `json:"vehicle_plate,omitempty"`
	// VehiclePlates holds the value of the "vehicle_plates" field.
	VehiclePlates []string `json:"vehicle_plates,omitempty"`
	// Company holds the value of the "company" field.
	Company string `json:"company,omitempty"`
	// Visits holds the value of the "visits" field.
	Visits int `json:"visits,omitempty"`
	// LastVisitAt holds the value of the "last_visit_at" field.
	LastVisitAt *time.Time `json:"last_visit_at,omitempty"`
	// LastHostUnitID holds the value of the "last_host_unit_id" field.
	LastHostUnitID *uuid.UUID `json:"last_host_unit_id,omitempty"`
	// Status holds the value of the "status" field.
	Status visitor.Status `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Visitor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case visitor.FieldLastHostUnitID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case visitor.FieldMetadata, visitor.FieldVehiclePlates:
			values[i] = new([]byte)
		case visitor.FieldVisits:
			values[i] = new(sql.NullInt64)
		case visitor.FieldName, visitor.FieldPhone, visitor.FieldIDNumberHash, visitor.FieldIDNumberHint, visitor.FieldVehiclePlate, visitor.FieldCompany, visitor.FieldStatus, visitor.FieldNotes:
			values[i] = new(sql.NullString)
		case visitor.FieldCreatedAt, visitor.FieldUpdatedAt, visitor.FieldLastVisitAt:
			values[i] = new(sql.NullTime)
		case visitor.FieldID, visitor.FieldTenantID, visitor.FieldPropertyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Visitor fields.
func (_m *Visitor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case visitor.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case visitor.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case visitor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case visitor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case visitor.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case visitor.FieldPropertyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field property_id", values[i])
			} else if value != nil {
				_m.PropertyID = *value
			}
		case visitor.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case visitor.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case visitor.FieldIDNumberHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_number_hash", values[i])
			} else if value.Valid {
				_m.IDNumberHash = value.String
			}
		case visitor.FieldIDNumberHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id_number_hint", values[i])
			} else if value.Valid {
				_m.IDNumberHint = value.String
			}
		case visitor.FieldVehiclePlate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vehicle_plate", values[i])
			} else if value.Valid {
				_m.VehiclePlate = value.String
			}
		case visitor.FieldVehiclePlates:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field vehicle_plates", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.VehiclePlates); err != nil {
					return fmt.Errorf("unmarshal field vehicle_plates: %w", err)
				}
			}
		case visitor.FieldCompany:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company", values[i])
			} else if value.Valid {
				_m.Company = value.String
			}
		case visitor.FieldVisits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field visits", values[i])
			} else if value.Valid {
				_m.Visits = int(value.Int64)
			}
		case visitor.FieldLastVisitAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_visit_at", values[i])
			} else if value.Valid {
				_m.LastVisitAt = new(time.Time)
				*_m.LastVisitAt = value.Time
			}
		case visitor.FieldLastHostUnitID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field last_host_unit_id", values[i])
			} else if value.Valid {
				_m.LastHostUnitID = new(uuid.UUID)
				*_m.LastHostUnitID = *value.S.(*uuid.UUID)
			}
		case visitor.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = visitor.Status(value.String)
			}
		case visitor.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Visitor.
// This includes values selected through modifiers, order, etc.
func (_m *Visitor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Visitor.
// Note that you need to call Visitor.Unwrap() before calling this method if this Visitor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Visitor) Update() *VisitorUpdateOne {
	return NewVisitorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Visitor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Visitor) Unwrap() *Visitor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Visitor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Visitor) String() string {
	var builder strings.Builder
	builder.WriteString("Visitor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("property_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertyID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("id_number_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("id_number_hint=")
	builder.WriteString(_m.IDNumberHint)
	builder.WriteString(", ")
	builder.WriteString("vehicle_plate=")
	builder.WriteString(_m.VehiclePlate)
	builder.WriteString(", ")
	builder.WriteString("vehicle_plates=")
	builder.WriteString(fmt.Sprintf("%v", _m.VehiclePlates))
	builder.WriteString(", ")
	builder.WriteString("company=")
	builder.WriteString(_m.Company)
	builder.WriteString(", ")
	builder.WriteString("visits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visits))
	builder.WriteString(", ")
	if v := _m.LastVisitAt; v != nil {
		builder.WriteString("last_visit_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastHostUnitID; v != nil {
		builder.WriteString("last_host_unit_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// Visitors is a parsable slice of Visitor.
type Visitors []*Visitor
