// Code generated by ent, DO NOT EDIT.

package unit

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the unit type in the database.
	Label = "unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldPropertyID holds the string denoting the property_id field in the database.
	FieldPropertyID = "property_id"
	// FieldBlockID holds the string denoting the block_id field in the database.
	FieldBlockID = "block_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldUnitType holds the string denoting the unit_type field in the database.
	FieldUnitType = "unit_type"
	// FieldUse holds the string denoting the use field in the database.
	FieldUse = "use"
	// FieldBedrooms holds the string denoting the bedrooms field in the database.
	FieldBedrooms = "bedrooms"
	// FieldBathrooms holds the string denoting the bathrooms field in the database.
	FieldBathrooms = "bathrooms"
	// FieldSizeSqm holds the string denoting the size_sqm field in the database.
	FieldSizeSqm = "size_sqm"
	// FieldPlotSizeSqm holds the string denoting the plot_size_sqm field in the database.
	FieldPlotSizeSqm = "plot_size_sqm"
	// FieldFloor holds the string denoting the floor field in the database.
	FieldFloor = "floor"
	// FieldEntitlement holds the string denoting the entitlement field in the database.
	FieldEntitlement = "entitlement"
	// FieldParkingBays holds the string denoting the parking_bays field in the database.
	FieldParkingBays = "parking_bays"
	// FieldFurnished holds the string denoting the furnished field in the database.
	FieldFurnished = "furnished"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldSaleStatus holds the string denoting the sale_status field in the database.
	FieldSaleStatus = "sale_status"
	// FieldOccupancyStatus holds the string denoting the occupancy_status field in the database.
	FieldOccupancyStatus = "occupancy_status"
	// FieldRentable holds the string denoting the rentable field in the database.
	FieldRentable = "rentable"
	// FieldHandedOverAt holds the string denoting the handed_over_at field in the database.
	FieldHandedOverAt = "handed_over_at"
	// FieldFeatures holds the string denoting the features field in the database.
	FieldFeatures = "features"
	// FieldPhotos holds the string denoting the photos field in the database.
	FieldPhotos = "photos"
	// FieldWalkingOrder holds the string denoting the walking_order field in the database.
	FieldWalkingOrder = "walking_order"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCustomFields holds the string denoting the custom_fields field in the database.
	FieldCustomFields = "custom_fields"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// EdgeProperty holds the string denoting the property edge name in mutations.
	EdgeProperty = "property"
	// EdgeBlock holds the string denoting the block edge name in mutations.
	EdgeBlock = "block"
	// EdgeParties holds the string denoting the parties edge name in mutations.
	EdgeParties = "parties"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// Table holds the table name of the unit in the database.
	Table = "units"
	// PropertyTable is the table that holds the property relation/edge.
	PropertyTable = "units"
	// PropertyInverseTable is the table name for the Property entity.
	// It exists in this package in order to avoid circular dependency with the "property" package.
	PropertyInverseTable = "properties"
	// PropertyColumn is the table column denoting the property relation/edge.
	PropertyColumn = "property_id"
	// BlockTable is the table that holds the block relation/edge.
	BlockTable = "units"
	// BlockInverseTable is the table name for the Block entity.
	// It exists in this package in order to avoid circular dependency with the "block" package.
	BlockInverseTable = "blocks"
	// BlockColumn is the table column denoting the block relation/edge.
	BlockColumn = "block_id"
	// PartiesTable is the table that holds the parties relation/edge.
	PartiesTable = "unit_parties"
	// PartiesInverseTable is the table name for the UnitParty entity.
	// It exists in this package in order to avoid circular dependency with the "unitparty" package.
	PartiesInverseTable = "unit_parties"
	// PartiesColumn is the table column denoting the parties relation/edge.
	PartiesColumn = "unit_id"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "unit_accounts"
	// AccountsInverseTable is the table name for the UnitAccount entity.
	// It exists in this package in order to avoid circular dependency with the "unitaccount" package.
	AccountsInverseTable = "unit_accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "unit_id"
)

// Columns holds all SQL columns for unit fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldMetadata,
	FieldPropertyID,
	FieldBlockID,
	FieldCode,
	FieldUnitType,
	FieldUse,
	FieldBedrooms,
	FieldBathrooms,
	FieldSizeSqm,
	FieldPlotSizeSqm,
	FieldFloor,
	FieldEntitlement,
	FieldParkingBays,
	FieldFurnished,
	FieldPhase,
	FieldSaleStatus,
	FieldOccupancyStatus,
	FieldRentable,
	FieldHandedOverAt,
	FieldFeatures,
	FieldPhotos,
	FieldWalkingOrder,
	FieldStatus,
	FieldCustomFields,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/bengobox/maskani-api/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultUnitType holds the default value on creation for the "unit_type" field.
	DefaultUnitType string
	// DefaultEntitlement holds the default value on creation for the "entitlement" field.
	DefaultEntitlement func() decimal.Decimal
	// DefaultParkingBays holds the default value on creation for the "parking_bays" field.
	DefaultParkingBays int
	// DefaultFurnished holds the default value on creation for the "furnished" field.
	DefaultFurnished bool
	// DefaultRentable holds the default value on creation for the "rentable" field.
	DefaultRentable bool
	// DefaultWalkingOrder holds the default value on creation for the "walking_order" field.
	DefaultWalkingOrder int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Use defines the type for the "use" enum field.
type Use string

// UseResidential is the default value of the Use enum.
const DefaultUse = UseResidential

// Use values.
const (
	UseResidential Use = "residential"
	UseOffice      Use = "office"
	UseRetail      Use = "retail"
	UseIndustrial  Use = "industrial"
	UseParking     Use = "parking"
	UseLand        Use = "land"
	UseStorage     Use = "storage"
	UseOther       Use = "other"
)

func (u Use) String() string {
	return string(u)
}

// UseValidator is a validator for the "use" field enum values. It is called by the builders before save.
func UseValidator(u Use) error {
	switch u {
	case UseResidential, UseOffice, UseRetail, UseIndustrial, UseParking, UseLand, UseStorage, UseOther:
		return nil
	default:
		return fmt.Errorf("unit: invalid enum value for use field: %q", u)
	}
}

// SaleStatus defines the type for the "sale_status" enum field.
type SaleStatus string

// SaleStatusNotForSale is the default value of the SaleStatus enum.
const DefaultSaleStatus = SaleStatusNotForSale

// SaleStatus values.
const (
	SaleStatusNotForSale     SaleStatus = "not_for_sale"
	SaleStatusAvailable      SaleStatus = "available"
	SaleStatusReserved       SaleStatus = "reserved"
	SaleStatusUnderAgreement SaleStatus = "under_agreement"
	SaleStatusFullyPaid      SaleStatus = "fully_paid"
	SaleStatusHandedOver     SaleStatus = "handed_over"
	SaleStatusTitled         SaleStatus = "titled"
	SaleStatusInDefault      SaleStatus = "in_default"
)

func (ss SaleStatus) String() string {
	return string(ss)
}

// SaleStatusValidator is a validator for the "sale_status" field enum values. It is called by the builders before save.
func SaleStatusValidator(ss SaleStatus) error {
	switch ss {
	case SaleStatusNotForSale, SaleStatusAvailable, SaleStatusReserved, SaleStatusUnderAgreement, SaleStatusFullyPaid, SaleStatusHandedOver, SaleStatusTitled, SaleStatusInDefault:
		return nil
	default:
		return fmt.Errorf("unit: invalid enum value for sale_status field: %q", ss)
	}
}

// OccupancyStatus defines the type for the "occupancy_status" enum field.
type OccupancyStatus string

// OccupancyStatusVacant is the default value of the OccupancyStatus enum.
const DefaultOccupancyStatus = OccupancyStatusVacant

// OccupancyStatus values.
const (
	OccupancyStatusVacant          OccupancyStatus = "vacant"
	OccupancyStatusOwnerOccupied   OccupancyStatus = "owner_occupied"
	OccupancyStatusTenanted        OccupancyStatus = "tenanted"
	OccupancyStatusUnderRenovation OccupancyStatus = "under_renovation"
	OccupancyStatusComingVacant    OccupancyStatus = "coming_vacant"
)

func (os OccupancyStatus) String() string {
	return string(os)
}

// OccupancyStatusValidator is a validator for the "occupancy_status" field enum values. It is called by the builders before save.
func OccupancyStatusValidator(os OccupancyStatus) error {
	switch os {
	case OccupancyStatusVacant, OccupancyStatusOwnerOccupied, OccupancyStatusTenanted, OccupancyStatusUnderRenovation, OccupancyStatusComingVacant:
		return nil
	default:
		return fmt.Errorf("unit: invalid enum value for occupancy_status field: %q", os)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusArchived:
		return nil
	default:
		return fmt.Errorf("unit: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Unit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPropertyID orders the results by the property_id field.
func ByPropertyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPropertyID, opts...).ToFunc()
}

// ByBlockID orders the results by the block_id field.
func ByBlockID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByUnitType orders the results by the unit_type field.
func ByUnitType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitType, opts...).ToFunc()
}

// ByUse orders the results by the use field.
func ByUse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUse, opts...).ToFunc()
}

// ByBedrooms orders the results by the bedrooms field.
func ByBedrooms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBedrooms, opts...).ToFunc()
}

// ByBathrooms orders the results by the bathrooms field.
func ByBathrooms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBathrooms, opts...).ToFunc()
}

// BySizeSqm orders the results by the size_sqm field.
func BySizeSqm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeSqm, opts...).ToFunc()
}

// ByPlotSizeSqm orders the results by the plot_size_sqm field.
func ByPlotSizeSqm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlotSizeSqm, opts...).ToFunc()
}

// ByFloor orders the results by the floor field.
func ByFloor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFloor, opts...).ToFunc()
}

// ByEntitlement orders the results by the entitlement field.
func ByEntitlement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntitlement, opts...).ToFunc()
}

// ByParkingBays orders the results by the parking_bays field.
func ByParkingBays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParkingBays, opts...).ToFunc()
}

// ByFurnished orders the results by the furnished field.
func ByFurnished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFurnished, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// BySaleStatus orders the results by the sale_status field.
func BySaleStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSaleStatus, opts...).ToFunc()
}

// ByOccupancyStatus orders the results by the occupancy_status field.
func ByOccupancyStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccupancyStatus, opts...).ToFunc()
}

// ByRentable orders the results by the rentable field.
func ByRentable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRentable, opts...).ToFunc()
}

// ByHandedOverAt orders the results by the handed_over_at field.
func ByHandedOverAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandedOverAt, opts...).ToFunc()
}

// ByWalkingOrder orders the results by the walking_order field.
func ByWalkingOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalkingOrder, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByPropertyField orders the results by property field.
func ByPropertyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPropertyStep(), sql.OrderByField(field, opts...))
	}
}

// ByBlockField orders the results by block field.
func ByBlockField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlockStep(), sql.OrderByField(field, opts...))
	}
}

// ByPartiesCount orders the results by parties count.
func ByPartiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPartiesStep(), opts...)
	}
}

// ByParties orders the results by parties terms.
func ByParties(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPartiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPropertyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PropertyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PropertyTable, PropertyColumn),
	)
}
func newBlockStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlockInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlockTable, BlockColumn),
	)
}
func newPartiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PartiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PartiesTable, PartiesColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
