// Code generated by ent, DO NOT EDIT.

package serviceschedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContractID applies equality check predicate on the "contract_id" field. It's identical to ContractIDEQ.
func ContractID(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldContractID, v))
}

// PropertyID applies equality check predicate on the "property_id" field. It's identical to PropertyIDEQ.
func PropertyID(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldPropertyID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldName, v))
}

// TimeWindow applies equality check predicate on the "time_window" field. It's identical to TimeWindowEQ.
func TimeWindow(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldTimeWindow, v))
}

// Zone applies equality check predicate on the "zone" field. It's identical to ZoneEQ.
func Zone(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldZone, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldActive, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotNull(FieldMetadata))
}

// ContractIDEQ applies the EQ predicate on the "contract_id" field.
func ContractIDEQ(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldContractID, v))
}

// ContractIDNEQ applies the NEQ predicate on the "contract_id" field.
func ContractIDNEQ(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldContractID, v))
}

// ContractIDIn applies the In predicate on the "contract_id" field.
func ContractIDIn(vs ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldContractID, vs...))
}

// ContractIDNotIn applies the NotIn predicate on the "contract_id" field.
func ContractIDNotIn(vs ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldContractID, vs...))
}

// ContractIDGT applies the GT predicate on the "contract_id" field.
func ContractIDGT(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldContractID, v))
}

// ContractIDGTE applies the GTE predicate on the "contract_id" field.
func ContractIDGTE(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldContractID, v))
}

// ContractIDLT applies the LT predicate on the "contract_id" field.
func ContractIDLT(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldContractID, v))
}

// ContractIDLTE applies the LTE predicate on the "contract_id" field.
func ContractIDLTE(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldContractID, v))
}

// PropertyIDEQ applies the EQ predicate on the "property_id" field.
func PropertyIDEQ(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldPropertyID, v))
}

// PropertyIDNEQ applies the NEQ predicate on the "property_id" field.
func PropertyIDNEQ(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldPropertyID, v))
}

// PropertyIDIn applies the In predicate on the "property_id" field.
func PropertyIDIn(vs ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldPropertyID, vs...))
}

// PropertyIDNotIn applies the NotIn predicate on the "property_id" field.
func PropertyIDNotIn(vs ...uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldPropertyID, vs...))
}

// PropertyIDGT applies the GT predicate on the "property_id" field.
func PropertyIDGT(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldPropertyID, v))
}

// PropertyIDGTE applies the GTE predicate on the "property_id" field.
func PropertyIDGTE(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldPropertyID, v))
}

// PropertyIDLT applies the LT predicate on the "property_id" field.
func PropertyIDLT(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldPropertyID, v))
}

// PropertyIDLTE applies the LTE predicate on the "property_id" field.
func PropertyIDLTE(v uuid.UUID) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldPropertyID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldContainsFold(FieldName, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v Frequency) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v Frequency) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...Frequency) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...Frequency) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldFrequency, vs...))
}

// DaysIsNil applies the IsNil predicate on the "days" field.
func DaysIsNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIsNull(FieldDays))
}

// DaysNotNil applies the NotNil predicate on the "days" field.
func DaysNotNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotNull(FieldDays))
}

// TimeWindowEQ applies the EQ predicate on the "time_window" field.
func TimeWindowEQ(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldTimeWindow, v))
}

// TimeWindowNEQ applies the NEQ predicate on the "time_window" field.
func TimeWindowNEQ(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldTimeWindow, v))
}

// TimeWindowIn applies the In predicate on the "time_window" field.
func TimeWindowIn(vs ...string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldTimeWindow, vs...))
}

// TimeWindowNotIn applies the NotIn predicate on the "time_window" field.
func TimeWindowNotIn(vs ...string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldTimeWindow, vs...))
}

// TimeWindowGT applies the GT predicate on the "time_window" field.
func TimeWindowGT(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldTimeWindow, v))
}

// TimeWindowGTE applies the GTE predicate on the "time_window" field.
func TimeWindowGTE(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldTimeWindow, v))
}

// TimeWindowLT applies the LT predicate on the "time_window" field.
func TimeWindowLT(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldTimeWindow, v))
}

// TimeWindowLTE applies the LTE predicate on the "time_window" field.
func TimeWindowLTE(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldTimeWindow, v))
}

// TimeWindowContains applies the Contains predicate on the "time_window" field.
func TimeWindowContains(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldContains(FieldTimeWindow, v))
}

// TimeWindowHasPrefix applies the HasPrefix predicate on the "time_window" field.
func TimeWindowHasPrefix(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldHasPrefix(FieldTimeWindow, v))
}

// TimeWindowHasSuffix applies the HasSuffix predicate on the "time_window" field.
func TimeWindowHasSuffix(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldHasSuffix(FieldTimeWindow, v))
}

// TimeWindowIsNil applies the IsNil predicate on the "time_window" field.
func TimeWindowIsNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIsNull(FieldTimeWindow))
}

// TimeWindowNotNil applies the NotNil predicate on the "time_window" field.
func TimeWindowNotNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotNull(FieldTimeWindow))
}

// TimeWindowEqualFold applies the EqualFold predicate on the "time_window" field.
func TimeWindowEqualFold(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEqualFold(FieldTimeWindow, v))
}

// TimeWindowContainsFold applies the ContainsFold predicate on the "time_window" field.
func TimeWindowContainsFold(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldContainsFold(FieldTimeWindow, v))
}

// ZoneEQ applies the EQ predicate on the "zone" field.
func ZoneEQ(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldZone, v))
}

// ZoneNEQ applies the NEQ predicate on the "zone" field.
func ZoneNEQ(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldZone, v))
}

// ZoneIn applies the In predicate on the "zone" field.
func ZoneIn(vs ...string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIn(FieldZone, vs...))
}

// ZoneNotIn applies the NotIn predicate on the "zone" field.
func ZoneNotIn(vs ...string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotIn(FieldZone, vs...))
}

// ZoneGT applies the GT predicate on the "zone" field.
func ZoneGT(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGT(FieldZone, v))
}

// ZoneGTE applies the GTE predicate on the "zone" field.
func ZoneGTE(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldGTE(FieldZone, v))
}

// ZoneLT applies the LT predicate on the "zone" field.
func ZoneLT(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLT(FieldZone, v))
}

// ZoneLTE applies the LTE predicate on the "zone" field.
func ZoneLTE(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldLTE(FieldZone, v))
}

// ZoneContains applies the Contains predicate on the "zone" field.
func ZoneContains(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldContains(FieldZone, v))
}

// ZoneHasPrefix applies the HasPrefix predicate on the "zone" field.
func ZoneHasPrefix(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldHasPrefix(FieldZone, v))
}

// ZoneHasSuffix applies the HasSuffix predicate on the "zone" field.
func ZoneHasSuffix(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldHasSuffix(FieldZone, v))
}

// ZoneIsNil applies the IsNil predicate on the "zone" field.
func ZoneIsNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIsNull(FieldZone))
}

// ZoneNotNil applies the NotNil predicate on the "zone" field.
func ZoneNotNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotNull(FieldZone))
}

// ZoneEqualFold applies the EqualFold predicate on the "zone" field.
func ZoneEqualFold(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEqualFold(FieldZone, v))
}

// ZoneContainsFold applies the ContainsFold predicate on the "zone" field.
func ZoneContainsFold(v string) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldContainsFold(FieldZone, v))
}

// ChecklistIsNil applies the IsNil predicate on the "checklist" field.
func ChecklistIsNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldIsNull(FieldChecklist))
}

// ChecklistNotNil applies the NotNil predicate on the "checklist" field.
func ChecklistNotNil() predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNotNull(FieldChecklist))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.FieldNEQ(FieldActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceSchedule) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceSchedule) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceSchedule) predicate.ServiceSchedule {
	return predicate.ServiceSchedule(sql.NotPredicates(p))
}
