// Code generated by ent, DO NOT EDIT.

package meterreading

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldUpdatedAt, v))
}

// RoundID applies equality check predicate on the "round_id" field. It's identical to RoundIDEQ.
func RoundID(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldRoundID, v))
}

// MeterID applies equality check predicate on the "meter_id" field. It's identical to MeterIDEQ.
func MeterID(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldMeterID, v))
}

// UnitID applies equality check predicate on the "unit_id" field. It's identical to UnitIDEQ.
func UnitID(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldUnitID, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldPeriod, v))
}

// Reading applies equality check predicate on the "reading" field. It's identical to ReadingEQ.
func Reading(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldReading, v))
}

// PreviousReading applies equality check predicate on the "previous_reading" field. It's identical to PreviousReadingEQ.
func PreviousReading(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldPreviousReading, v))
}

// Consumption applies equality check predicate on the "consumption" field. It's identical to ConsumptionEQ.
func Consumption(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldConsumption, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldReadAt, v))
}

// ReadBy applies equality check predicate on the "read_by" field. It's identical to ReadByEQ.
func ReadBy(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldReadBy, v))
}

// PhotoKey applies equality check predicate on the "photo_key" field. It's identical to PhotoKeyEQ.
func PhotoKey(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldPhotoKey, v))
}

// IsEstimated applies equality check predicate on the "is_estimated" field. It's identical to IsEstimatedEQ.
func IsEstimated(v bool) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldIsEstimated, v))
}

// VerifiedBy applies equality check predicate on the "verified_by" field. It's identical to VerifiedByEQ.
func VerifiedBy(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldVerifiedBy, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldNotes, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldUpdatedAt, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldMetadata))
}

// RoundIDEQ applies the EQ predicate on the "round_id" field.
func RoundIDEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldRoundID, v))
}

// RoundIDNEQ applies the NEQ predicate on the "round_id" field.
func RoundIDNEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldRoundID, v))
}

// RoundIDIn applies the In predicate on the "round_id" field.
func RoundIDIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldRoundID, vs...))
}

// RoundIDNotIn applies the NotIn predicate on the "round_id" field.
func RoundIDNotIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldRoundID, vs...))
}

// RoundIDGT applies the GT predicate on the "round_id" field.
func RoundIDGT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldRoundID, v))
}

// RoundIDGTE applies the GTE predicate on the "round_id" field.
func RoundIDGTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldRoundID, v))
}

// RoundIDLT applies the LT predicate on the "round_id" field.
func RoundIDLT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldRoundID, v))
}

// RoundIDLTE applies the LTE predicate on the "round_id" field.
func RoundIDLTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldRoundID, v))
}

// RoundIDIsNil applies the IsNil predicate on the "round_id" field.
func RoundIDIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldRoundID))
}

// RoundIDNotNil applies the NotNil predicate on the "round_id" field.
func RoundIDNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldRoundID))
}

// MeterIDEQ applies the EQ predicate on the "meter_id" field.
func MeterIDEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldMeterID, v))
}

// MeterIDNEQ applies the NEQ predicate on the "meter_id" field.
func MeterIDNEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldMeterID, v))
}

// MeterIDIn applies the In predicate on the "meter_id" field.
func MeterIDIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldMeterID, vs...))
}

// MeterIDNotIn applies the NotIn predicate on the "meter_id" field.
func MeterIDNotIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldMeterID, vs...))
}

// UnitIDEQ applies the EQ predicate on the "unit_id" field.
func UnitIDEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldUnitID, v))
}

// UnitIDNEQ applies the NEQ predicate on the "unit_id" field.
func UnitIDNEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldUnitID, v))
}

// UnitIDIn applies the In predicate on the "unit_id" field.
func UnitIDIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldUnitID, vs...))
}

// UnitIDNotIn applies the NotIn predicate on the "unit_id" field.
func UnitIDNotIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldUnitID, vs...))
}

// UnitIDGT applies the GT predicate on the "unit_id" field.
func UnitIDGT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldUnitID, v))
}

// UnitIDGTE applies the GTE predicate on the "unit_id" field.
func UnitIDGTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldUnitID, v))
}

// UnitIDLT applies the LT predicate on the "unit_id" field.
func UnitIDLT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldUnitID, v))
}

// UnitIDLTE applies the LTE predicate on the "unit_id" field.
func UnitIDLTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldUnitID, v))
}

// UnitIDIsNil applies the IsNil predicate on the "unit_id" field.
func UnitIDIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldUnitID))
}

// UnitIDNotNil applies the NotNil predicate on the "unit_id" field.
func UnitIDNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldUnitID))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldPeriod, v))
}

// PeriodContains applies the Contains predicate on the "period" field.
func PeriodContains(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldContains(FieldPeriod, v))
}

// PeriodHasPrefix applies the HasPrefix predicate on the "period" field.
func PeriodHasPrefix(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldHasPrefix(FieldPeriod, v))
}

// PeriodHasSuffix applies the HasSuffix predicate on the "period" field.
func PeriodHasSuffix(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldHasSuffix(FieldPeriod, v))
}

// PeriodEqualFold applies the EqualFold predicate on the "period" field.
func PeriodEqualFold(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEqualFold(FieldPeriod, v))
}

// PeriodContainsFold applies the ContainsFold predicate on the "period" field.
func PeriodContainsFold(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldContainsFold(FieldPeriod, v))
}

// ReadingEQ applies the EQ predicate on the "reading" field.
func ReadingEQ(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldReading, v))
}

// ReadingNEQ applies the NEQ predicate on the "reading" field.
func ReadingNEQ(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldReading, v))
}

// ReadingIn applies the In predicate on the "reading" field.
func ReadingIn(vs ...decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldReading, vs...))
}

// ReadingNotIn applies the NotIn predicate on the "reading" field.
func ReadingNotIn(vs ...decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldReading, vs...))
}

// ReadingGT applies the GT predicate on the "reading" field.
func ReadingGT(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldReading, v))
}

// ReadingGTE applies the GTE predicate on the "reading" field.
func ReadingGTE(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldReading, v))
}

// ReadingLT applies the LT predicate on the "reading" field.
func ReadingLT(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldReading, v))
}

// ReadingLTE applies the LTE predicate on the "reading" field.
func ReadingLTE(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldReading, v))
}

// PreviousReadingEQ applies the EQ predicate on the "previous_reading" field.
func PreviousReadingEQ(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldPreviousReading, v))
}

// PreviousReadingNEQ applies the NEQ predicate on the "previous_reading" field.
func PreviousReadingNEQ(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldPreviousReading, v))
}

// PreviousReadingIn applies the In predicate on the "previous_reading" field.
func PreviousReadingIn(vs ...decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldPreviousReading, vs...))
}

// PreviousReadingNotIn applies the NotIn predicate on the "previous_reading" field.
func PreviousReadingNotIn(vs ...decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldPreviousReading, vs...))
}

// PreviousReadingGT applies the GT predicate on the "previous_reading" field.
func PreviousReadingGT(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldPreviousReading, v))
}

// PreviousReadingGTE applies the GTE predicate on the "previous_reading" field.
func PreviousReadingGTE(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldPreviousReading, v))
}

// PreviousReadingLT applies the LT predicate on the "previous_reading" field.
func PreviousReadingLT(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldPreviousReading, v))
}

// PreviousReadingLTE applies the LTE predicate on the "previous_reading" field.
func PreviousReadingLTE(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldPreviousReading, v))
}

// PreviousReadingIsNil applies the IsNil predicate on the "previous_reading" field.
func PreviousReadingIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldPreviousReading))
}

// PreviousReadingNotNil applies the NotNil predicate on the "previous_reading" field.
func PreviousReadingNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldPreviousReading))
}

// ConsumptionEQ applies the EQ predicate on the "consumption" field.
func ConsumptionEQ(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldConsumption, v))
}

// ConsumptionNEQ applies the NEQ predicate on the "consumption" field.
func ConsumptionNEQ(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldConsumption, v))
}

// ConsumptionIn applies the In predicate on the "consumption" field.
func ConsumptionIn(vs ...decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldConsumption, vs...))
}

// ConsumptionNotIn applies the NotIn predicate on the "consumption" field.
func ConsumptionNotIn(vs ...decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldConsumption, vs...))
}

// ConsumptionGT applies the GT predicate on the "consumption" field.
func ConsumptionGT(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldConsumption, v))
}

// ConsumptionGTE applies the GTE predicate on the "consumption" field.
func ConsumptionGTE(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldConsumption, v))
}

// ConsumptionLT applies the LT predicate on the "consumption" field.
func ConsumptionLT(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldConsumption, v))
}

// ConsumptionLTE applies the LTE predicate on the "consumption" field.
func ConsumptionLTE(v decimal.Decimal) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldConsumption, v))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v time.Time) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldReadAt, v))
}

// ReadByEQ applies the EQ predicate on the "read_by" field.
func ReadByEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldReadBy, v))
}

// ReadByNEQ applies the NEQ predicate on the "read_by" field.
func ReadByNEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldReadBy, v))
}

// ReadByIn applies the In predicate on the "read_by" field.
func ReadByIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldReadBy, vs...))
}

// ReadByNotIn applies the NotIn predicate on the "read_by" field.
func ReadByNotIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldReadBy, vs...))
}

// ReadByGT applies the GT predicate on the "read_by" field.
func ReadByGT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldReadBy, v))
}

// ReadByGTE applies the GTE predicate on the "read_by" field.
func ReadByGTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldReadBy, v))
}

// ReadByLT applies the LT predicate on the "read_by" field.
func ReadByLT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldReadBy, v))
}

// ReadByLTE applies the LTE predicate on the "read_by" field.
func ReadByLTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldReadBy, v))
}

// ReadByIsNil applies the IsNil predicate on the "read_by" field.
func ReadByIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldReadBy))
}

// ReadByNotNil applies the NotNil predicate on the "read_by" field.
func ReadByNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldReadBy))
}

// PhotoKeyEQ applies the EQ predicate on the "photo_key" field.
func PhotoKeyEQ(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldPhotoKey, v))
}

// PhotoKeyNEQ applies the NEQ predicate on the "photo_key" field.
func PhotoKeyNEQ(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldPhotoKey, v))
}

// PhotoKeyIn applies the In predicate on the "photo_key" field.
func PhotoKeyIn(vs ...string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldPhotoKey, vs...))
}

// PhotoKeyNotIn applies the NotIn predicate on the "photo_key" field.
func PhotoKeyNotIn(vs ...string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldPhotoKey, vs...))
}

// PhotoKeyGT applies the GT predicate on the "photo_key" field.
func PhotoKeyGT(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldPhotoKey, v))
}

// PhotoKeyGTE applies the GTE predicate on the "photo_key" field.
func PhotoKeyGTE(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldPhotoKey, v))
}

// PhotoKeyLT applies the LT predicate on the "photo_key" field.
func PhotoKeyLT(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldPhotoKey, v))
}

// PhotoKeyLTE applies the LTE predicate on the "photo_key" field.
func PhotoKeyLTE(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldPhotoKey, v))
}

// PhotoKeyContains applies the Contains predicate on the "photo_key" field.
func PhotoKeyContains(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldContains(FieldPhotoKey, v))
}

// PhotoKeyHasPrefix applies the HasPrefix predicate on the "photo_key" field.
func PhotoKeyHasPrefix(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldHasPrefix(FieldPhotoKey, v))
}

// PhotoKeyHasSuffix applies the HasSuffix predicate on the "photo_key" field.
func PhotoKeyHasSuffix(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldHasSuffix(FieldPhotoKey, v))
}

// PhotoKeyIsNil applies the IsNil predicate on the "photo_key" field.
func PhotoKeyIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldPhotoKey))
}

// PhotoKeyNotNil applies the NotNil predicate on the "photo_key" field.
func PhotoKeyNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldPhotoKey))
}

// PhotoKeyEqualFold applies the EqualFold predicate on the "photo_key" field.
func PhotoKeyEqualFold(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEqualFold(FieldPhotoKey, v))
}

// PhotoKeyContainsFold applies the ContainsFold predicate on the "photo_key" field.
func PhotoKeyContainsFold(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldContainsFold(FieldPhotoKey, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldSource, vs...))
}

// IsEstimatedEQ applies the EQ predicate on the "is_estimated" field.
func IsEstimatedEQ(v bool) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldIsEstimated, v))
}

// IsEstimatedNEQ applies the NEQ predicate on the "is_estimated" field.
func IsEstimatedNEQ(v bool) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldIsEstimated, v))
}

// FlagsIsNil applies the IsNil predicate on the "flags" field.
func FlagsIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldFlags))
}

// FlagsNotNil applies the NotNil predicate on the "flags" field.
func FlagsNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldFlags))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldStatus, vs...))
}

// VerifiedByEQ applies the EQ predicate on the "verified_by" field.
func VerifiedByEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldVerifiedBy, v))
}

// VerifiedByNEQ applies the NEQ predicate on the "verified_by" field.
func VerifiedByNEQ(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldVerifiedBy, v))
}

// VerifiedByIn applies the In predicate on the "verified_by" field.
func VerifiedByIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldVerifiedBy, vs...))
}

// VerifiedByNotIn applies the NotIn predicate on the "verified_by" field.
func VerifiedByNotIn(vs ...uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldVerifiedBy, vs...))
}

// VerifiedByGT applies the GT predicate on the "verified_by" field.
func VerifiedByGT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldVerifiedBy, v))
}

// VerifiedByGTE applies the GTE predicate on the "verified_by" field.
func VerifiedByGTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldVerifiedBy, v))
}

// VerifiedByLT applies the LT predicate on the "verified_by" field.
func VerifiedByLT(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldVerifiedBy, v))
}

// VerifiedByLTE applies the LTE predicate on the "verified_by" field.
func VerifiedByLTE(v uuid.UUID) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldVerifiedBy, v))
}

// VerifiedByIsNil applies the IsNil predicate on the "verified_by" field.
func VerifiedByIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldVerifiedBy))
}

// VerifiedByNotNil applies the NotNil predicate on the "verified_by" field.
func VerifiedByNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldVerifiedBy))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.MeterReading {
	return predicate.MeterReading(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.MeterReading {
	return predicate.MeterReading(sql.FieldContainsFold(FieldNotes, v))
}

// HasMeter applies the HasEdge predicate on the "meter" edge.
func HasMeter() predicate.MeterReading {
	return predicate.MeterReading(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MeterTable, MeterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMeterWith applies the HasEdge predicate on the "meter" edge with a given conditions (other predicates).
func HasMeterWith(preds ...predicate.Meter) predicate.MeterReading {
	return predicate.MeterReading(func(s *sql.Selector) {
		step := newMeterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MeterReading) predicate.MeterReading {
	return predicate.MeterReading(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MeterReading) predicate.MeterReading {
	return predicate.MeterReading(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MeterReading) predicate.MeterReading {
	return predicate.MeterReading(sql.NotPredicates(p))
}
