// Code generated by ent, DO NOT EDIT.

package maintenanceschedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/maskani-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// PropertyID applies equality check predicate on the "property_id" field. It's identical to PropertyIDEQ.
func PropertyID(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldPropertyID, v))
}

// AssetRef applies equality check predicate on the "asset_ref" field. It's identical to AssetRefEQ.
func AssetRef(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldAssetRef, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldTitle, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldCategory, v))
}

// NextDueAt applies equality check predicate on the "next_due_at" field. It's identical to NextDueAtEQ.
func NextDueAt(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldNextDueAt, v))
}

// DefaultVendorID applies equality check predicate on the "default_vendor_id" field. It's identical to DefaultVendorIDEQ.
func DefaultVendorID(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldDefaultVendorID, v))
}

// DefaultEmployeeID applies equality check predicate on the "default_employee_id" field. It's identical to DefaultEmployeeIDEQ.
func DefaultEmployeeID(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldDefaultEmployeeID, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldActive, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotNull(FieldMetadata))
}

// PropertyIDEQ applies the EQ predicate on the "property_id" field.
func PropertyIDEQ(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldPropertyID, v))
}

// PropertyIDNEQ applies the NEQ predicate on the "property_id" field.
func PropertyIDNEQ(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldPropertyID, v))
}

// PropertyIDIn applies the In predicate on the "property_id" field.
func PropertyIDIn(vs ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldPropertyID, vs...))
}

// PropertyIDNotIn applies the NotIn predicate on the "property_id" field.
func PropertyIDNotIn(vs ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldPropertyID, vs...))
}

// PropertyIDGT applies the GT predicate on the "property_id" field.
func PropertyIDGT(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldPropertyID, v))
}

// PropertyIDGTE applies the GTE predicate on the "property_id" field.
func PropertyIDGTE(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldPropertyID, v))
}

// PropertyIDLT applies the LT predicate on the "property_id" field.
func PropertyIDLT(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldPropertyID, v))
}

// PropertyIDLTE applies the LTE predicate on the "property_id" field.
func PropertyIDLTE(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldPropertyID, v))
}

// AssetRefEQ applies the EQ predicate on the "asset_ref" field.
func AssetRefEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldAssetRef, v))
}

// AssetRefNEQ applies the NEQ predicate on the "asset_ref" field.
func AssetRefNEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldAssetRef, v))
}

// AssetRefIn applies the In predicate on the "asset_ref" field.
func AssetRefIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldAssetRef, vs...))
}

// AssetRefNotIn applies the NotIn predicate on the "asset_ref" field.
func AssetRefNotIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldAssetRef, vs...))
}

// AssetRefGT applies the GT predicate on the "asset_ref" field.
func AssetRefGT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldAssetRef, v))
}

// AssetRefGTE applies the GTE predicate on the "asset_ref" field.
func AssetRefGTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldAssetRef, v))
}

// AssetRefLT applies the LT predicate on the "asset_ref" field.
func AssetRefLT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldAssetRef, v))
}

// AssetRefLTE applies the LTE predicate on the "asset_ref" field.
func AssetRefLTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldAssetRef, v))
}

// AssetRefContains applies the Contains predicate on the "asset_ref" field.
func AssetRefContains(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContains(FieldAssetRef, v))
}

// AssetRefHasPrefix applies the HasPrefix predicate on the "asset_ref" field.
func AssetRefHasPrefix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasPrefix(FieldAssetRef, v))
}

// AssetRefHasSuffix applies the HasSuffix predicate on the "asset_ref" field.
func AssetRefHasSuffix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasSuffix(FieldAssetRef, v))
}

// AssetRefIsNil applies the IsNil predicate on the "asset_ref" field.
func AssetRefIsNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIsNull(FieldAssetRef))
}

// AssetRefNotNil applies the NotNil predicate on the "asset_ref" field.
func AssetRefNotNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotNull(FieldAssetRef))
}

// AssetRefEqualFold applies the EqualFold predicate on the "asset_ref" field.
func AssetRefEqualFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEqualFold(FieldAssetRef, v))
}

// AssetRefContainsFold applies the ContainsFold predicate on the "asset_ref" field.
func AssetRefContainsFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContainsFold(FieldAssetRef, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContainsFold(FieldTitle, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContainsFold(FieldCategory, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v Frequency) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v Frequency) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...Frequency) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...Frequency) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldFrequency, vs...))
}

// NextDueAtEQ applies the EQ predicate on the "next_due_at" field.
func NextDueAtEQ(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldNextDueAt, v))
}

// NextDueAtNEQ applies the NEQ predicate on the "next_due_at" field.
func NextDueAtNEQ(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldNextDueAt, v))
}

// NextDueAtIn applies the In predicate on the "next_due_at" field.
func NextDueAtIn(vs ...time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldNextDueAt, vs...))
}

// NextDueAtNotIn applies the NotIn predicate on the "next_due_at" field.
func NextDueAtNotIn(vs ...time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldNextDueAt, vs...))
}

// NextDueAtGT applies the GT predicate on the "next_due_at" field.
func NextDueAtGT(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldNextDueAt, v))
}

// NextDueAtGTE applies the GTE predicate on the "next_due_at" field.
func NextDueAtGTE(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldNextDueAt, v))
}

// NextDueAtLT applies the LT predicate on the "next_due_at" field.
func NextDueAtLT(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldNextDueAt, v))
}

// NextDueAtLTE applies the LTE predicate on the "next_due_at" field.
func NextDueAtLTE(v time.Time) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldNextDueAt, v))
}

// DefaultVendorIDEQ applies the EQ predicate on the "default_vendor_id" field.
func DefaultVendorIDEQ(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldDefaultVendorID, v))
}

// DefaultVendorIDNEQ applies the NEQ predicate on the "default_vendor_id" field.
func DefaultVendorIDNEQ(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldDefaultVendorID, v))
}

// DefaultVendorIDIn applies the In predicate on the "default_vendor_id" field.
func DefaultVendorIDIn(vs ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldDefaultVendorID, vs...))
}

// DefaultVendorIDNotIn applies the NotIn predicate on the "default_vendor_id" field.
func DefaultVendorIDNotIn(vs ...uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldDefaultVendorID, vs...))
}

// DefaultVendorIDGT applies the GT predicate on the "default_vendor_id" field.
func DefaultVendorIDGT(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldDefaultVendorID, v))
}

// DefaultVendorIDGTE applies the GTE predicate on the "default_vendor_id" field.
func DefaultVendorIDGTE(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldDefaultVendorID, v))
}

// DefaultVendorIDLT applies the LT predicate on the "default_vendor_id" field.
func DefaultVendorIDLT(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldDefaultVendorID, v))
}

// DefaultVendorIDLTE applies the LTE predicate on the "default_vendor_id" field.
func DefaultVendorIDLTE(v uuid.UUID) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldDefaultVendorID, v))
}

// DefaultVendorIDIsNil applies the IsNil predicate on the "default_vendor_id" field.
func DefaultVendorIDIsNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIsNull(FieldDefaultVendorID))
}

// DefaultVendorIDNotNil applies the NotNil predicate on the "default_vendor_id" field.
func DefaultVendorIDNotNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotNull(FieldDefaultVendorID))
}

// DefaultEmployeeIDEQ applies the EQ predicate on the "default_employee_id" field.
func DefaultEmployeeIDEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDNEQ applies the NEQ predicate on the "default_employee_id" field.
func DefaultEmployeeIDNEQ(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDIn applies the In predicate on the "default_employee_id" field.
func DefaultEmployeeIDIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIn(FieldDefaultEmployeeID, vs...))
}

// DefaultEmployeeIDNotIn applies the NotIn predicate on the "default_employee_id" field.
func DefaultEmployeeIDNotIn(vs ...string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotIn(FieldDefaultEmployeeID, vs...))
}

// DefaultEmployeeIDGT applies the GT predicate on the "default_employee_id" field.
func DefaultEmployeeIDGT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGT(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDGTE applies the GTE predicate on the "default_employee_id" field.
func DefaultEmployeeIDGTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldGTE(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDLT applies the LT predicate on the "default_employee_id" field.
func DefaultEmployeeIDLT(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLT(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDLTE applies the LTE predicate on the "default_employee_id" field.
func DefaultEmployeeIDLTE(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldLTE(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDContains applies the Contains predicate on the "default_employee_id" field.
func DefaultEmployeeIDContains(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContains(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDHasPrefix applies the HasPrefix predicate on the "default_employee_id" field.
func DefaultEmployeeIDHasPrefix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasPrefix(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDHasSuffix applies the HasSuffix predicate on the "default_employee_id" field.
func DefaultEmployeeIDHasSuffix(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldHasSuffix(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDIsNil applies the IsNil predicate on the "default_employee_id" field.
func DefaultEmployeeIDIsNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldIsNull(FieldDefaultEmployeeID))
}

// DefaultEmployeeIDNotNil applies the NotNil predicate on the "default_employee_id" field.
func DefaultEmployeeIDNotNil() predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNotNull(FieldDefaultEmployeeID))
}

// DefaultEmployeeIDEqualFold applies the EqualFold predicate on the "default_employee_id" field.
func DefaultEmployeeIDEqualFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEqualFold(FieldDefaultEmployeeID, v))
}

// DefaultEmployeeIDContainsFold applies the ContainsFold predicate on the "default_employee_id" field.
func DefaultEmployeeIDContainsFold(v string) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldContainsFold(FieldDefaultEmployeeID, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.FieldNEQ(FieldActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MaintenanceSchedule) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MaintenanceSchedule) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MaintenanceSchedule) predicate.MaintenanceSchedule {
	return predicate.MaintenanceSchedule(sql.NotPredicates(p))
}
